### ISSUE TITLE
How to predict the input time series separately

### ISSUE THREAD

**Issue by yuyudiandian** [thuml/Autoformer#1]
I saw that the function “predict”,but it seems to have some problems.
![image](https://user-images.githubusercontent.com/71555221/140059817-253072ec-2984-4115-a6f3-a88127bec6ad.png)
There doesn't seem to be this “Dataset_Pred” ，how can I get it?
![image](https://user-images.githubusercontent.com/71555221/140059902-4d301931-6187-40b8-a90f-254d4fb8ea96.png)

**Comment by wuhaixu2016** [comment]
Hi, you can view the 'predict' as the model serving. 

When you adopt the model to real-world applications, the future is unseen (also without supervision). You can use this API to deal with this situation. This also means, 'predict' is like 'test', but without the metric.

This part has nothing to do with our experiments in the paper. It is just a reference for real-world applications.

Many thanks for your questions. I will add the 'datast_pred' soon.

**Comment by wuhaixu2016** [comment]
Hi, I have added the dataloader of predict. See dataloader.py for details. 
You can use the argument  '--do_predict' for prediction.
