### ISSUE TITLE
Check the correlation calculation code in metrics.py line 10

### ISSUE THREAD

**Issue by 943fansi** [thuml/Autoformer#102]
`  d = np.sqrt(((true - true.mean(0)) ** 2 * (pred - pred.mean(0)) ** 2).sum(0))`
maybe 
` d = np.sqrt(((true - true.mean(0)) ** 2).sum(0) * ((pred - pred.mean(0)) ** 2).sum(0))`?

**Comment by wuhaixu2016** [comment]
Thanks for this issue, we have fixed this bug in the latest commit:https://github.com/thuml/Autoformer/commit/9d67034cf9f5b049d0a3ea436c10b834939b1635.
