### ISSUE TITLE
Can this model predict the multi-targets? If it can, could u tell me how to fix the code?

### ISSUE THREAD

**Issue by successdang99** [thuml/Autoformer#103]

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

Can you provide more details about "multi-targets"?

(1) If you mean multivariate forecasting, we have already supported this.

(2) If you refer to multi-task learning (including anomaly detection, forecasting, and classification), I think you can try multiple final MLP projectors. 
Further, if you are interested in the multi-task learning in time series, maybe you can find our latest paper helpful: https://arxiv.org/abs/2210.02186
