### ISSUE TITLE
Bug while directly running scripts

### ISSUE THREAD

**Issue by hchen463** [thuml/Autoformer#107]
Hi,

The following error pops out when I directly run the script. Can you let me know what's going on? Thanks.

Autoformer-main/exp/exp_main.py", line 248, in test
    preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
IndexError: tuple index out of range

**Comment by ljc20010323** [comment]
Hi,
I also have the same question. Can you let me know how to solve

**Comment by hchen463** [comment]
in my example the shape of preds is (90,) cuz the last element in the batch does not share the same size as the previous elements, you can either ignore the last batch or use concat operation to construct preds.

**Comment by cxqs** [comment]
please ,how to  ignore the last batch?such as verify "preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])" as "preds = preds.reshape(-1, preds.shape[-2])"?
