### ISSUE TITLE
--itr argument 

### ISSUE THREAD

**Issue by Niharikajo** [thuml/Autoformer#108]
Hello,

I was trying multivariate forecasting using the Autoformer model. 

In run.py there is an argument --itr 

1.  Is it used when there is more than one script in the [.sh](https://github.com/thuml/Autoformer/blob/main/scripts/ETT_script/Autoformer_ETTh1.sh) file?

2. I have a single script in the [script(.sh)](https://github.com/thuml/Autoformer/blob/main/scripts/ETT_script/Autoformer_ETTh1.sh) file,  when I had given --itr as 2 the same experiment had repeated  twice. However, I noticed that during the second round of testing, the error metrics were significantly lower.  Can you please explain why?  

Thank you
Niharika Joshi

**Comment by wuhaixu2016** [comment]
Hi, this argument is to repeat the experiments multiple times, and the paper, we repeat the experiments three times and report the averaged values.

So, I think in real-world applications, you can just fix the random see and set args.itr as 1.
