### ISSUE TITLE
Snapshot of input data 

### ISSUE THREAD

**Issue by oremnirv** [thuml/Autoformer#109]
Thank you very much for the lovely paper. 

I'm trying to implement your model. 

Can I kindly ask for a snapshot of what the (x_enc, x_mark_enc, x_dec, x_mark_dec) look like? i.e., an example of one row from the data frame (preferably in a pandas view with column names)? 

Thank you!

**Comment by wuhaixu2016** [comment]
Hi, sorry for the delayed response.
Let us take the encoder inputs as the example:
x_enc is in the shape of B*L*C, where B is the batch dimension, L is the temporal dimension and C is the variate dimension.
x_mark_enc is in the shape of B*L*5, which is the date information of each time point. For each time point of each sample, the 1*1*5 dimension organized in (month, day, weekday, hour, minute).
