### ISSUE TITLE
top K

### ISSUE THREAD

**Issue by oremnirv** [thuml/Autoformer#110]
Clarification question: 
In algorithm 2 in your paper,
how do you go from the softmax weights having K dimensions to R variable with L dimensions?  

Thank you

**Comment by wuhaixu2016** [comment]
Hi, this process is quite clear in Code.
Line 38-48 in https://github.com/thuml/Autoformer/blob/main/layers/AutoCorrelation.py
We will adopt the K softmax weights to aggregate K delayed length-L time series.
