### ISSUE TITLE
static real labels

### ISSUE THREAD

**Issue by dialuser** [thuml/Autoformer#112]
Hi thanks for open-sourcing the nice package.
My problem has 13 real-valued static variables. The brute-force way is to repeat all static variables for each sample time. Is there a better way to incorporate the static variables without repeating the static values.

Thanks.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest, 
If you only have 13 static variables as the past observation, this problem may not be a time series forecasting task. A simple MLP may also perform well. Would you please provide more details?

**Comment by dialuser** [comment]
Hi

Sorry I meant 13 static variables describing station characteristics and 5 other auxiliary dynamic variables per station. The target variable may or may not be part of the predictors.  This is because the target variable may not be observed all the time, whereas the auxiliary time series are always continuous. Autoformer currently offers Many-to-many and many-to-single, but they do not fit my problem exactly. Thanks.

**Comment by wuhaixu2016** [comment]
Thanks for your detailed descriptions.
(1) For the encoder part: I think it is a reasonable way to repeat the 13 static variables for each time stamp, which can make the static variables align with the dynamic variables.
(2) For the decoder part: 
- If the target variable is a static variable (do not change over time), you can just adopt an MLP as the decoder.
- If the target variable is a dynamic variable (change over time), you can just adopt an Autoformer decoder and only calculate the loss on the observed times.

Generally,  you can view the Autoformer encoder as a feature extractor to this problem. Hope this is helpful to you~
