### ISSUE TITLE
 IndexError: tuple index out of range

### ISSUE THREAD

**Issue by cxqs** [thuml/Autoformer#113]
File "/root/autodl-tmp/Autoformer2021/exp/exp_main.py", line 248, in test
    preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
IndexError: tuple index out of range
![image](https://user-images.githubusercontent.com/25101517/215375741-6250eeba-c730-4769-ba12-3eb749317562.png)

**Comment by wuhaixu2016** [comment]
Hi, thanks for your response!

We have fixed this problem in the latest commit: https://github.com/thuml/Autoformer/commit/fd047f16981de2a659882795b1441c884f456601
