### ISSUE TITLE
decomposition visualization

### ISSUE THREAD

**Issue by zhouliang-yu** [thuml/Autoformer#115]
Hey, Thx so much for sharing this repo. 
I have some sort of questions related to the decomposition visualization：
what is the tool to visualize the decomposed seasonal and trend series, any util API provided in your code?
[![R4eZq.png](https://i.328888.xyz/2023/02/10/R4eZq.png)](https://imgloc.com/i/R4eZq)

**Comment by wuhaixu2016** [comment]
Hi, you can directly adopt the `visual` function in https://github.com/thuml/Autoformer/blob/main/utils/tools.py.
The visualized components are `trend_part` and `seasonal_part` in line 94 of https://github.com/thuml/Autoformer/blob/main/models/Autoformer.py

**Comment by zhouliang-yu** [comment]
yeah its cool，thx！

________________________________
发件人: wuhaixu2016 ***@***.***>
发送时间: Saturday, February 11, 2023 9:40:48 PM
收件人: thuml/Autoformer ***@***.***>
抄送: Zhouliang Yu (SDS, 120040077) ***@***.***>; Author ***@***.***>
主题: Re: [thuml/Autoformer] decomposition visualization (Issue #115)


Hi, you can directly adopt the visual function in https://github.com/thuml/Autoformer/blob/main/utils/tools.py.
The visualized components are trend_part and seasonal_part in line 94 of https://github.com/thuml/Autoformer/blob/main/models/Autoformer.py

―
