### ISSUE TITLE
Problem in reproducing results in ETT dataset

### ISSUE THREAD

**Issue by MarcAntoineAlex** [thuml/Autoformer#12]
## Hi Haixu, I really like the idea in your paper, but I've encountered some problem when I tried to reproduce the results for ETTh1 dataset. 
I've used the latest version of your code, and got the following results which are quite weird

pred_len 24: mse:0.4061545729637146, mae:0.4404798150062561
pred_len 48: mse:0.48272132873535156, mae:0.46404534578323364
pred_len 168: mse:0.49321380257606506, mae:0.48073211312294006
pred_len 336: mse:0.5146851539611816, mae:0.4921443462371826
pred_len 720: mse:0.49855655431747437, mae:0.5004686117172241

Environment : linux, pytorch@1.10.0, python3.8, cuda10.2, cudnn7.6.5_0. 

Also, why the ETTh1 performance of informer in your paper is different from that in the original paper of informer? The MSE for pred_len 720 is up to 3.379, whereas in the original paper of informer, the MSE is 1.215. 
I've attached the result log and the script I used (adapted to slurm system). 
Best regards
[log and script.zip](https://github.com/thuml/Autoformer/files/7887724/log.and.script.zip)

**Comment by ShelveyJ** [comment]
Hi,  In the original paper of autoformer,  the mse for pred_len 720  which is 3.379 is the result of ETTm1, not ETTh1. You can see the result of ETTh1 when using informer  in Appendix A

**Comment by ddz16** [comment]
> 

3.379 is the result of ETTm2

**Comment by ddz16** [comment]
> Hi, In the original paper of autoformer, the mse for pred_len 720 which is 3.379 is the result of ETTm1, not ETTh1. You can see the result of ETTh1 when using informer in Appendix A

3.379 is the result of ETTm2, not ETTm1

**Comment by wuhaixu2016** [comment]
Many thanks to @ddz16  and @ShelveyJ  for clarification. 

The main paper provides the results about ETTm2, the full ETT benchmark can be found in Appendix A.
