### ISSUE TITLE
forecasting future using autoformer

### ISSUE THREAD

**Issue by ayizii** [thuml/Autoformer#120]
Hello, Thank you for your amazing work. I was wondering, is it possible to use Autoformer to forecast the future unknown values based on previous predictions and trends. Something similar to this: 

![image](https://user-images.githubusercontent.com/48940876/219447975-39246433-7341-4aee-9afd-ff77db2d4731.png)

How can I achieve this ?

**Comment by wuhaixu2016** [comment]
sure, you may find the predict function in line 272 helpful https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py
