### ISSUE TITLE
noisy results

### ISSUE THREAD

**Issue by guetaro** [thuml/Autoformer#121]
Hi,

Thanks for this Git, great work!

When using the git i recive noisy results (for example, the ETTm dataset):

![test_Autoformer_ETTm1_ftS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtTrue_test_0](https://user-images.githubusercontent.com/110457498/220275619-6d2ba7c0-08d6-4b6f-89bb-25648dd47c98.png)

As you can see the prediction is noisy while the ground truth isn't so much. I would like to know if it's the expected behavior or such a system or I'm doing somthing wrong (the plot is done using pred.flatten() and true.flatten()). The numeric MSE results are fine.

Thank you in advance.

**Comment by wuhaixu2016** [comment]
Hi, would you please detail the legend. I will take the orange line as prediction and the blue line as ground truth.

Over-smoothing is a shared problem of deep models. Maybe you can try some sharpness loss function in addition to the MSE.

**Comment by guetaro** [comment]
Sorry for that, the blue is the prediction and the orange is the groud truth actually.
I avaraged the results for every window (since there are windows of 96 samples each).
After avaraging the results seems better
Hope its a valid way

thank again

**Comment by wuhaixu2016** [comment]
I think this is because the encoder-decoder framework is too redundant for short-term forecasting. Maybe you can replace the decoder as a simple MLP along the temporal dimension.

Or you may find our latest work TimesNet (https://github.com/thuml/TimesNet) useful, which is also evaluated on M4.

**Comment by guetaro** [comment]
Thanks again for the help.

I maybe worng but I can't find the code itself in the repository you shared (only the readme and images). When the code itself will be uploaded?

I'll consider replacing the decoder with other layers.

Thanks

**Comment by wuhaixu2016** [comment]
You may need to read the first sentence of the README.md carefully.

<img width="924" alt="截屏2023-02-27 下午8 48 37" src="https://user-images.githubusercontent.com/24385030/221567967-8d0e4ea7-0926-4b84-a566-f041b658ad5c.png">
