### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by zxc262403** [thuml/Autoformer#123]
![image](https://user-images.githubusercontent.com/52236902/220962867-42324344-432f-4839-b4f0-32fe343de7dc.png)
您好，如上图所见，exp.tarin()中return了self.model，而在run.py中却并没有变量去接收，这样是不是可能造成内存上的问题呢？

**Comment by wuhaixu2016** [comment]
您好，python有自动的内存回收机制，我觉得不会占用很多。不过为了保证代码的规范，我们在最近的commit中已经删去了返回值，感谢您的建议！
