### ISSUE TITLE
您好，请问下论文中的结果都是默认参数得到的吗？我好像用默认参数效果差很多

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Autoformer#126]

**Comment by wuhaixu2016** [comment]
您好，请问具体是哪个setting呢，我们在push script前都跑过，是可以完整复现论文结果的

**Comment by wuhaixu2016** [comment]
我觉得这份代码的复现是没有问题的，具体可以参考之前的issue
https://github.com/thuml/Autoformer/issues/19
