### ISSUE TITLE
Informer的实现好像和官方有些不一致？

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Autoformer#127]
您好，看代码的时候发现informer的实现和官方的实现好像还是有些出入的，informer中的EncoderStack好像被忽略了，请问这样做是出于什么考虑的呢？另外去除EncoderStack对informer的预测效果影响有多大呢？

**Comment by wuhaixu2016** [comment]
您好，informer中EncoderStack的目的是减少计算量，去掉之后效果会更好。
