### ISSUE TITLE
关于AutoCorr的过程有些疑问

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Autoformer#128]
您好，关于autocorrelation我有一些疑问，为什么进行attention时roll的操作是使序列左移而不是右移呢？我的理解是auto-corr相当于计算了一个时延的权重，然后按照这个将相应时延的信息加入，而因为预测时用到的是序列尾部的信息，所以roll应该沿时间轴右移从而将对应的时延信息加入到尾部？

**Comment by wuhaixu2016** [comment]
您好，这个其实对应着学到的lag的大小，例如一个长度为96的序列，lag 1是左移1位，lag 95则等价于右移1位，这个是可以有数据自己计算出来的。

**Comment by ownnaruto** [comment]
哦哦，我好像有些明白了，lag是学习到的，所以左右其实没有区别？

**Comment by wuhaixu2016** [comment]
嗯嗯，您的理解是正确的
