### ISSUE TITLE
Problem in reproducing results with `--features MS`

### ISSUE THREAD

**Issue by omerlux** [thuml/Autoformer#13]
# Hi! I have read your paper and tried to reproduce the results for the ETT datasets.

When trying to configure `--features MS` - which means that I want to predict univariate target using multivariate input, I see that the model's output still contains all the features ([bs x ts x 7] for ETTh1 for example).

I tried to fix it by changing `--c_out` to 1 instead of 7, but in the model, the trends vector is not fixed properly:
https://github.com/thuml/Autoformer/blob/4dd5f17c48bce56d842c5d094e9e9d02b17c1531/models/Autoformer.py#L94
So here, `seasonal_part` has a dimension of [bs x ts x 1] and `trend_part` has a dimension of [bs x ts x 7] (no error thrown because PyTorch allow this action to occur).

What is your implementation?

Thank you

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest!
(1) Our paper does not provide the benchmark for "Multivariate to Univariate". The paper only shows the "Multivariate to Multivariate" and "Univariate to Univariate". So, "reproduce" is suitable in this situation.

(2) The code about `MS` can be found in './exp/exp_main.py' line76, 146, 224. The operation for picking the last dimension variate is done **outside the model**. Thus, it is normal that the model output is [bs x ts x 7].

(3) If you want to save the extra parameter in the last projector. You can ref to the following steps:
- change the --c_out to 1
- add `trend_init=trend_init[:,:,-1:]` to line 83 of './models/Autoformer.py' 

Hope this will be helpful to you~

**Comment by omerlux** [comment]
Thank you for your quick response!

With regards to the code mentioned in './exp/exp_main.py' - my issue was that you picked the last dimension only for the targets (`batch_y`) and not for the model's outputs, which means that the loss criteria is based on dimensions 1 and 7, respectively.

Additionally, I agree with your suggestion in './models/Autoformer.py' but one needs to keep in mind that the dimension picking on `trend_init=trend_init[:,:,-1:]` should be done while considering the addition of `mean` in line 84.

Thanks again,

**Comment by wuhaixu2016** [comment]
Cool! Thanks for your suggestion.
I have updated the code for MS in https://github.com/thuml/Autoformer/commit/7f9ce3c58b73b4f4b1163e093f47550a5cdbc6d5
Hope this is helpful to you.
