### ISSUE TITLE
memroy leak

### ISSUE THREAD

**Issue by zxc262403** [thuml/Autoformer#130]
![image](https://user-images.githubusercontent.com/52236902/222061455-58bbfbf4-8a7f-44ee-9a8c-c3b6172fee7a.png)
您好，我们团队将Autoformer模型部署至Linux服务器上测试过程中发现，在exp.train()中的这段for循环中发现似乎会产生内存泄漏问题(内存不断增长，且始终不释放内存对象)，不知道您在调试过程中有没有类似的经历呢？
注1：exp.pred()中类似的for循环中也会产生内存泄漏问题，不过因pred_loader较小，问题并不明显
注2：exp.vali()中86行total_loss.append(loss)是否要修改成total_loss.append(loss.item())避免占据过多内存？

**Comment by zxc262403** [comment]
最后我们团队选择了开启进程池的方式解决了这个问题。

**Comment by wuhaixu2016** [comment]
您好，感谢您们的使用和贡献，如果可以的话，可以提一个pull request来解决这个bug，非常感谢！
