### ISSUE TITLE
handling with different input/output shapes

### ISSUE THREAD

**Issue by guetaro** [thuml/Autoformer#131]
Hi,

I would like to fit the algorithm so it will be able to handle different input/output shapes. does the algorithm support such a thing? if not, do you have an idea how to do so?

Thanks again

**Comment by wuhaixu2016** [comment]
Hi, you can change the argument enc_in, dec_in and c_out.

**Comment by wuhaixu2016** [comment]
Oh i understand you point now. You mean one certain model predict different future lengths? I think it is a great idea, but nobody has tested this strategy. 

However, Autoformer support this! You can just load the model and change the seq_len, pred_len as you want.
