### ISSUE TITLE
ValueError 问题

### ISSUE THREAD

**Issue by 821237374** [thuml/Autoformer#135]
您好，我执行了run.py以后，显示is_training、model_id、model、data是必要的。但是这几个值都有默认值，所以我就把这几项的required改成了False。再次执行时，会在data_factory.py中的print(flag, len(data_set))部分出现报错ValueError: __len__() should return >= 0。

我不清楚这是什么原因导致的，请求指导，谢谢！

**Comment by wuhaixu2016** [comment]
您好，可以直接使用bash命令运行给出的配置脚本，例如 https://github.com/thuml/Autoformer/blob/main/scripts/ETT_script/Autoformer_ETTh1.sh
