### ISSUE TITLE
Hi，想问一下可以在哪里添加超参数寻优代码呢？

### ISSUE THREAD

**Issue by Kivirrr** [thuml/Autoformer#137]
Hi，萌新想问一下如果想加入一些贝叶斯优化寻参或者启发式算法寻参的话，该把代码加在哪里呢？是在run.py那里吗，还是在那些exp_basic之类的文件里面呢？

**Comment by wuhaixu2016** [comment]
您好，可以放在run.py那里，超参数的定义都在那里

**Comment by daihaozxn** [comment]
您好，请问Autoformer论文中关于超参数（c，编码器层数，解码器层数等）的确定，是在每个数据集上分别进行网格搜索确定的么？我看这6个数据集上最后效果最优的编码器和解码器层数都相同，分别是2和1。
