### ISSUE TITLE
利用这个模型怎么实现回归呢？

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Autoformer#138]
目前觉得这个模型是实现了预测的功能，怎么实现输入和输出的分离，并进行回归预测呢？

**Comment by LY-must-win** [comment]
&nbsp; &nbsp; &nbsp;万分感谢您的解答，我还有疑问，就是我在调试您的代码后发现：①data_loder程序里看到您划分的训练集，验证集和测试集里除了时间以外包含了所有的变量，看到了您把OT也包含作为了模型输入的一部分，没有看到输入和输出的划分在哪，做回归预测应该是要划分的吧？②在exp_main模块里看到预测是个三维数组，如果只要预测OT，是不是只设置run.py模块下的features为MS，seq_len和label_len保持不变，pre_len设置为1就可以吗？但感觉这个是单步预测了。
&nbsp; &nbsp; &nbsp;目前我是做风电场风速回归预测的，输入和输出想分离开再输入模型训练，其中输入样本和标签是同时刻对应的，比如同一时刻多个输入对应一个输出那种，不是上时刻输入对应下个时刻输出，预测的话是测试输入数据的长度和预测输出长度一样就可以，比如我输入一个月数据训练，模型也能回归预测输出一个月数据，和线性回归做法差不多，最后只是预测OT这个标签。我的问题是，做这种回归预测需不需要分离输入和输出？如果需要的话可以方便告知下如何修改吗？挺想应用您这个模型作为我的首选。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月23日(周四) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuml/Autoformer] 利用这个模型怎么实现回归呢？ (Issue #138)




 
您好，可以在decoder最后增加一个linear层，就可以实现回归了～

**Comment by wuhaixu2016** [comment]
您好，关于MS setting 请见：https://github.com/thuml/Autoformer/issues/132
关于使用自己的数据集请见：https://github.com/thuml/Autoformer/issues/36

不好意思，我对具体应用场景不熟悉，需要您自己做针对性修改。

**Comment by LY-must-win** [comment]
> 您好，关于MS setting 请见：#132 关于使用自己的数据集请见：#36
> 
> 不好意思，我对具体应用场景不熟悉，需要您自己做针对性修改。

非常感谢您的解答，从大家提出的问题里我也受到了启发。

**Comment by SamuelWong77** [comment]
您好，我也在想问回归预测是否单纯MS设置下直接输出预测值，还是要调整dataloader 分离输入变量和输出变量。感觉要做一下实验。理论上很多时序预测场景都是根据某时刻的测量值比如传感器来预测一些状态值。
