### ISSUE TITLE
Exchange rate dataset length

### ISSUE THREAD

**Issue by Big-Tree** [thuml/Autoformer#14]
Hello, thanks for making your code public!

In your paper you say that the exchange rate dataset ranges from 1990 to 2016, however after downloading it using the link in the README.md there is only data from 1990 to 2010.  This gives the series a length of 7589.  After splitting with a ratio of 7:1:2, as given in the paper, the validation set has a length of just 759 which causes problems when trying to evaluate a forecast length of 720 and a history of 96.  Is there data missing from the dataset?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

（1）please see https://github.com/laiguokun/multivariate-time-series-data for the raw data (and data description) of Exchange-rate. In this repo, we add the manual-designed timestamps only to represent the time interval.

（2）I think you have some misunderstanding about the dataset splitting. Please refer to the `Dataset_Custom` class in ./data_provider/data_loader.py for more details.
