### ISSUE TITLE
真实结果图与预测的结果图相差很大

### ISSUE THREAD

**Issue by Dyw08** [thuml/Autoformer#140]
您好，我跑自己的数据集mse在0.26左右，（我跑ETTh1才0.45），但是为什么我的数据集的真实图与预测图相差很大？

**Comment by wuhaixu2016** [comment]
您好，感谢关注！时序预测是一个很困难的任务，具体的预测效果和您的数据量、数据的平稳性都是相关的，一般来说更好的模型会达到更好的效果，但是不一定保证可以准确预测未来。
