### ISSUE TITLE
预测波形震荡严重

### ISSUE THREAD

**Issue by zhongmengyi** [thuml/Autoformer#141]
你好，我运行自己的数据集来预测降雨量，多次尝试修改了超参数之后，出来的预测图像还是和真实值有很大出入，出现了很多震荡的波形，我想减小预测波形的震荡，有什么好的建议吗
![CN7KVYPT71WP9W8}C VL($W](https://user-images.githubusercontent.com/117893921/228732129-9adb69c8-ee5c-43b1-b7d5-bdaae611add8.png)

**Comment by wuhaixu2016** [comment]
您好，这个和损失函数有关，可以在MSE损失函数之外，增加一个未来真实和预测结果的频率之差，这个会显著改善波形相关的问题

**Comment by zhongmengyi** [comment]
您好，增加未来真实值与预测结果之差这一部分可以详细说说吗？非常感谢！

**Comment by wuhaixu2016** [comment]
比如使用这样的loss：||FFT(Y)-FFT(\hat{Y})||，Y和\hat{Y}分别是真实未来和预测的未来，相当于将MSE loss做在频域上

**Comment by wuhaixu2016** [comment]
不知道您有没有使用我们提到的这个频率loss

**Comment by zhongmengyi** [comment]
用weather.csv的数据集预测的时候没有使用频率loss
