### ISSUE TITLE
跑自己数据集的问题。

### ISSUE THREAD

**Issue by xuyaojian123** [thuml/Autoformer#143]
您好，非常感谢你出色的工作，有个问题想请教您一下。如下所示，我有300天的太阳辐射强度数据，我要把最后十天的Radiation特征(290-299天)当作我的测试数据，其他特征不用预测。请问一下由于我的特征里面没有date特征，只有Day表示第几天的数据，而且天与天之间的数据是不连续的，只给出了当天早上6点-晚上20点的数据，因为其他时间段太阳辐射强度为0。请问，如果我想预测最后十天(290-299天)的辐射强度Radiation改如何设置呢，谢谢。
![image](https://user-images.githubusercontent.com/51220835/230337704-8afbeeee-d505-4ae8-b2e3-712ae56236c8.png)

**Comment by wuhaixu2016** [comment]
您好，感谢关注
（1）关于date字段，这个可以模仿我们已经给出的数据集进行设置，例如weather，是datetime格式
（2）关于时间不连续情况，其实不用在意这个间断，因为您这个数据集的间断情况是固定的，因此对于预测影响不大，只需要保证输入长度是周期的整数倍即可

**Comment by xuyaojian123** [comment]
> 您好，感谢关注 （1）关于date字段，这个可以模仿我们已经给出的数据集进行设置，例如weather，是datetime格式 （2）关于时间不连续情况，其实不用在意这个间断，因为您这个数据集的间断情况是固定的，因此对于预测影响不大，只需要保证输入长度是周期的整数倍即可

您好，我的数据集里面没有年、月、日的特征，只有Day（表示第几天）的特征，weather数据集date是有这些信息的。 您的意思是说自己给他构造一个年月日特征吗？

**Comment by wuhaixu2016** [comment]
是的，可以直接构造，这个没有影响
