### ISSUE TITLE
自相关函数的计算

### ISSUE THREAD

**Issue by Wty1122** [thuml/Autoformer#144]
很荣幸能关注到您出色的工作，但是在计算自相关函数时，我有一个不解的地方。
自相关函数是根据维纳-辛钦定理得到的，即：功率谱密度是自相关函数的反傅里叶变换。根据论文和代码给出的解释是通过计算序列的傅里叶变换的模的平方，进而进行反傅里叶变换来得到自相关系数。但是“傅里叶变换的模的平方”表示的不是能量谱密度吗？而且根据周期图法，功率谱应该是对序列进行离散傅立叶变换得X(k)，然后再取其幅值的平方，并除以N得到的。
由于对相关内容了解的不是很深入，所以感到很困惑，谢谢。

**Comment by wuhaixu2016** [comment]
您好，可以在这里看到解答：https://en.wikipedia.org/wiki/Autocorrelation#Efficient_computation
