### ISSUE TITLE
关于代码复现

### ISSUE THREAD

**Issue by jiyunfei12138** [thuml/Autoformer#147]
大佬你好，我想请问这个可以在PC端的Pycharm里实现复现吗，我之前用informer的开源代码跑我的数据集虽然MAE等指标很低但是预测效果曲线很不理想，所以试试这个，我把数据集下载好后直接运行run.py会提示
![image](https://user-images.githubusercontent.com/106957845/235301356-e29bbde9-c825-46a0-9434-6ed29e50b2bf.png)
也就是没有输入参数，但是我看main里已经设置好了，用Terminal运行（python -u run.py   --is_training 1   --root_path ./ETDataset/ETT-small/   --data_path ETTh1.csv   --model_id ETTh1_96_24   --model Autoformer   --data ETTh1   --features M   --seq_len 96   --label_len 48   --pred_len 24   --e_layers 2   --d_layers 1   --factor 3   --enc_in 7   --dec_in 7   --c_out 7   --des 'Exp'   --itr 1）的话又会报错
![image](https://user-images.githubusercontent.com/106957845/235301415-beeeb0b5-3fa0-4fdc-a762-d48ff43ee2ae.png)
所以很是困扰，你们都是用Linux跑的吗

**Comment by jiyunfei12138** [comment]
> 大佬你好，我想请问这个可以在PC端的Pycharm里实现复现吗，我之前用informer的开源代码跑我的数据集虽然MAE等指标很低但是预测效果曲线很不理想，所以试试这个，我把数据集下载好后直接运行run.py会提示 ![image](https://user-images.githubusercontent.com/106957845/235301356-e29bbde9-c825-46a0-9434-6ed29e50b2bf.png) 也就是没有输入参数，但是我看main里已经设置好了，用Terminal运行（python -u run.py --is_training 1 --root_path ./ETDataset/ETT-small/ --data_path ETTh1.csv --model_id ETTh1_96_24 --model Autoformer --data ETTh1 --features M --seq_len 96 --label_len 48 --pred_len 24 --e_layers 2 --d_layers 1 --factor 3 --enc_in 7 --dec_in 7 --c_out 7 --des 'Exp' --itr 1）的话又会报错 ![image](https://user-images.githubusercontent.com/106957845/235301415-beeeb0b5-3fa0-4fdc-a762-d48ff43ee2ae.png) 所以很是困扰，你们都是用Linux跑的吗

把几个required=True删掉可以跑了，但还是报这个错：
![image](https://user-images.githubusercontent.com/106957845/235343965-5cb1ac60-2787-41c3-a71e-4e80ac0dc87a.png)

**Comment by wuhaixu2016** [comment]
您好，感谢关注，我们使用的环境都是linux，暂时不支持windows。
如果您之前在window中跑通过informer，可以将informer的模型替换为：https://github.com/thuml/Autoformer/blob/main/models/Autoformer.py
