### ISSUE TITLE
Some doubts about the ILI dataset

### ISSUE THREAD

**Issue by TommyNan** [thuml/Autoformer#148]
Thank you for your work and collection of the dataset. However, I have some doubts about the ILI dataset. 
In all related works,  the data from 2002 to 2017 in the ILI dataset is the same as the data provided by the website (can be downloaded from https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html). However, for the data after 2017/1/3 in the ILI dataset(index: 785), the data in the dataset is inconsistent with that on the website (2017-). Although the gap between the two is small, will it affect the experimental results?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your detailed experiment.
We collect the data in March, 2021. I think this is beacuse that CDC corrects the data after that time. 
I think it is ok if you only adopt this as a forecasting bachmark, since the temporal dependencies within the dataset is unchanged.

**Comment by TommyNan** [comment]
Thanks for your answer!
