### ISSUE TITLE
关于预测结果作图的问题

### ISSUE THREAD

**Issue by jiyunfei12138** [thuml/Autoformer#150]
作者你好，首先感谢大佬公开代码，然后请问test_result里的预测结果pdf的标号0.20.40是什么意思呢？为什么是隔20个命名，这些设置是在代码的哪个部分？
![image](https://github.com/thuml/Autoformer/assets/106957845/b46cb1cf-e74c-4aca-8095-86991d28a522)
还有要如何像论文附录E中 plot the last dimension of forecasting results，还请作者给予指点

**Comment by wuhaixu2016** [comment]
请见https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py的239行。
