### ISSUE TITLE
预测结果的概率分布随预测步长逐渐偏移

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Autoformer#151]
我实际要预测的目标数据是偏态分布的，这是正常状态的分布。Autoformer进行单步预测的时候，预测结果和实际的分布很接近，是偏态分布的，但是随着预测步长的增加，e.g.120步预测，预测结果的分布逐渐变为了正态分布，偏离了原来正常的偏态分布。这是什么原因造成的呢，能否调整？下图是KDE检验的结果。
![image](https://github.com/thuml/Autoformer/assets/103368413/f55e78a6-8229-43f4-802c-6eab71857c0a)

**Comment by wuhaixu2016** [comment]
您好，您关注到了一个非常重要的问题。
目前的深度模型是基于大数定律进行的，目标是拟合数据中主导地位的分布，所以预测会越来越偏向于正态分布。
我的判断是，现阶段所有预测模型都存在这样的问题，如果想要解决的话，需要额外的模型创新。

**Comment by LY-must-win** [comment]
好的，谢谢您的解答

**Comment by LY-must-win** [comment]
本质的原因是不是在于梯度下降算法假设了误差是正态分布的？

**Comment by wuhaixu2016** [comment]
您好，我觉得这个可能和损失函数有关，不过对于这个问题，目前大家研究的还比较少
