### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Dyw08** [thuml/Autoformer#152]
你好，我在运行自己的数据集时，enc_in, dec_in, c_out参数都改了，但是仍出现 ValueError: list.remove(x): x not in list，请问这个问题应该怎么解决？

**Comment by wuhaixu2016** [comment]
您好，可以提供一下数据集的样例吗，我看一下是什么情况～

**Comment by Dyw08** [comment]
不好意思，我已经解决了！谢谢！

**Comment by wuhaixu2016** [comment]
收到！感谢您的使用，抱歉回复的比较晚，祝您科研顺利～
