### ISSUE TITLE
对于output输出的一些疑问

### ISSUE THREAD

**Issue by sunxiaoyao-git** [thuml/Autoformer#153]
![image](https://github.com/thuml/Autoformer/assets/114201981/e4bc3db0-5a3e-4c3d-92b8-3e1a5360c2b9)
您好！想请教一个小地方。模型forward输出中已经截取了预测的部分后输出，然而在训练的时候又截取了一遍，这个做法是正确的嘛？还是是我的理解有问题呢？

**Comment by wuhaixu2016** [comment]
您好，感谢指出，这里的代码确实是重复的，主要为了防止在模型文件中忘记写截断导致报错。
