### ISSUE TITLE
请问怎么得到预测的正常结果？

### ISSUE THREAD

**Issue by wangcharliegithub** [thuml/Autoformer#159]
作者您好，在多变量预测单变量的任务中，我跑了自己的数据集，预测的结果保存在real_prediction.npy里，打印出来，基本上是介于(-1,1)的数据。您在处理数据的时候用了标准化，怎么恢复成正常数据呢，代码该如何改？急，先谢谢您的回复。
![屏幕截图 2023-06-16 115410](https://github.com/thuml/Autoformer/assets/26437123/6f118a5d-5c87-4283-b527-30e915ae647c)

**Comment by wuhaixu2016** [comment]
您好，请见：https://github.com/thuml/Autoformer/issues/6
