### ISSUE TITLE
Electricity Dataset Date Discrepancy 

### ISSUE THREAD

**Issue by Big-Tree** [thuml/Autoformer#16]
Hi, in the paper it's stated that the electricity dataset ranges from 2012 to 2014, however, in the CSV file, [linked](https://cloud.tsinghua.edu.cn/d/e1ccfff39ad541908bae/?p=%2Felectricity) to in README.md, the date column ranges from 2016 to 2019?

**Comment by wuhaixu2016** [comment]
Hi, Thanks for your interests.
The original data of ECL can be found in https://github.com/laiguokun/multivariate-time-series-data
In this repo, we pre-process the dataset by adding the timestamps. Thus, the date column is only used to indicate the temporal interval. For the real meaning of data, please refer to the original link.
