### ISSUE TITLE
请问预测时生成的real_prediction.npy是什么意思？

### ISSUE THREAD

**Issue by wangcharliegithub** [thuml/Autoformer#160]
作者您好！我跑了自己的数据集，是多变量预测单变量MS任务，我的参数设置为：python3 -u run.py --is_training 1  --root_path ./dataset/  --data_path PAB.csv  --model_id PAB_6172336  --model Autoformer  --data PAB  --features MS  --seq_len 32  --label_len 16  --pred_len 1  --e_layers 2 --d_layers 1  --factor 3  --enc_in 21  --dec_in 21  --c_out 1  --des 'Exp'  --freq 'b'  --itr 1 --target l6 --use_multi_gpu --devices 0,1,2,3 --do_predict 我想只预测一条数据，所以pred_len设置为1，请问我c_out参数设置的对吗？我对c_cout参数的理解就是：输出的维度。我的数据集每条数据有21维，--enc_in 21  --dec_in 21应该是正确的。我打印了real_prediction.npy，这个real_prediction.shape是(1, 1, 21)。我的理解：第一个1是说明这是单变量，中间的1代表预测长度pred_len，21表示预测结果的维度。那么这21个数据中，哪个是预测的值？在我这个实验中，小白我觉得real_prediction.npy是不是只应该出现一个值。不懂，求教，感谢。
![屏幕截图 2023-06-18 110649](https://github.com/thuml/Autoformer/assets/26437123/7dd22390-da6f-4508-8e13-dd56c692c382)

**Comment by wangcharliegithub** [comment]
我的target设置的是l6列，请问是不是这21个数据中第6个是预测值？

**Comment by wuhaixu2016** [comment]
您好，请关注：https://github.com/thuml/Autoformer/blob/main/data_provider/data_loader.py#L291C19-L291C19
Predcit函数上只进行一次预测，所以保存的结果只会保留一个样例的预测结果。
