### ISSUE TITLE
why r2_scores are negative?

### ISSUE THREAD

**Issue by vishnu803** [thuml/Autoformer#161]
I recently reviewd your work and on testing data you were using so  mse evaluation metric but by printing r2_scores on the test data your r2_scores they arre badly failing with negative r2_scores but while training r2_Scores are >0.85 for most of the cases when i print that indicate a clear overfitting.

is that the case or am i missing anything!

**Comment by wuhaixu2016** [comment]
Hi, I think this problem is solved in email.
