### ISSUE TITLE
请问freq设置成12h会不允许？

### ISSUE THREAD

**Issue by Xizhang-Yao** [thuml/Autoformer#163]
* 我的数据集是以半天作为一个采样周期，因此freq为12h，但在TimeFeatureEmbedding处显示12h不允许。
![image](https://github.com/thuml/Autoformer/assets/56180978/87cd8cfe-d51d-4eb5-8077-7c46415ebf2d)

**Comment by wuhaixu2016** [comment]
您好，如果以12小时为周期，那么设置成‘h’即可，不会影响模型效果
