### ISSUE TITLE
How to determine the value of the factor?

### ISSUE THREAD

**Issue by zezhishao** [thuml/Autoformer#165]
Thanks for your great work, when I tested Autoformer on other datasets, I found that the hyperparameter `factor` plays an crucial role. So I am wondering how to determine the value of `factor`?

**Comment by wuhaixu2016** [comment]
Hi, the argument `factor` decides the number of aggregated sub-series. 

Thus, it should be set as the number of periods in the input sequence. For example, the input series is with length-72 and you have a significant period length as 24, then you need to set factor as 72/24=3

**Comment by zezhishao** [comment]
Thanks for your timely reply!
