### ISSUE TITLE
关于autoformer的自相关性计算问题

### ISSUE THREAD

**Issue by Yuanen-Pang** [thuml/Autoformer#170]
autoformer的思路让人耳目一新！有以下问题想要请教：
（1）计算完自相关系数τ1-τk后，是将序列往左依次移动τ1-τk步，可是自相关系数是计算的x(t)和x(t-τ)，那么不应该向右移动吗？
_比如对于τ=1,[1,2,3,4,5]您移动后变成[2,3,4,5,1]，然后乘以权重相加，不应该是[5,1,2,3,4]么，这样5和滞后的1才能对应。
（2）在论文的式4处，本层的τ1-3各自乘以权重再与前一层的τ相加；但在代码中，是τ1-3先相加再乘以权重再与前一层相加，这个如何理解呢？
（3）预测序列的做法是先给出均值，然后将其与模型得到的各个seasonal_part相加，对于长时间单调上升的序列怎么办的，seasonal_part的均值应该是0（不知道理解对了没），加起来均值也应该是0

**Comment by LY-must-win** [comment]
> autoformer的思路让人耳目一新！有以下问题想要请教： （1）计算完自相关系数τ1-τk后，是将序列往左依次移动τ1-τk步，可是自相关系数是计算的x(t)和x(t-τ)，那么不应该向右移动吗？ _比如对于τ=1,[1,2,3,4,5]您移动后变成[2,3,4,5,1]，然后乘以权重相加，不应该是[5,1,2,3,4]么，这样5和滞后的1才能对应。 （2）在论文的式4处，本层的τ1-3各自乘以权重再与前一层的τ相加；但在代码中，是τ1-3先相加再乘以权重再与前一层相加，这个如何理解呢？ （3）预测序列的做法是先给出均值，然后将其与模型得到的各个seasonal_part相加，对于长时间单调上升的序列怎么办的，seasonal_part的均值应该是0（不知道理解对了没），加起来均值也应该是0

我在做预测的时候，对于解码器最后结果的季节分解部分其均值并不为零，我也比较困惑这部分，不知道您是否遇到同样的问题

**Comment by wuhaixu2016** [comment]
您好，感谢关注
（1）这个与torch.roll的实现有关，具体移动数值的正负需要根据torch版本更新
（2）您也可以根据论文公式实现，对模型效果不会有影响，先相加再乘以权重可以减小参数量
（3）autoformer在decoder阶段会输出两个部分，一个是趋势项预测，一个是周期项预测，其中趋势项预测部分可以应对单调上升的序列，具体可以看论文图4的可视化。
季节预报均值不为0是可以预料的，因为这是深度模型的输出结果，因为在预报时主要考虑了周期项的建模，所以这一部分的预报会highlight周期特征。
