### ISSUE TITLE
关于自定义数据集训练效果的问题

### ISSUE THREAD

**Issue by nodfan** [thuml/Autoformer#171]
作者您好，我详细看了您 #35 & #143 的回答，如何理解 ”输入长度是周期的整数倍” 跟数据周期性呢？目前用默认参数训练以下dataset（MS, 48, target=close）的效果并不好，我该如何调整参数呢？谢谢您的解答.
[BTC.csv](https://github.com/thuml/Autoformer/files/11998687/BTC.csv)

**Comment by wuhaixu2016** [comment]
Hi, thanks for sharing your data. It seems that all your data are in a relative large value. You may find the normalization De-normalization technique proposed by Non-stationary Transformer useful. https://github.com/thuml/Nonstationary_Transformers
