### ISSUE TITLE
Electricity dataset

### ISSUE THREAD

**Issue by khairulislam** [thuml/Autoformer#175]
Hi, 
I was looking through the datasets, but I found two issues. 
1. The electricity dataset uploaded in both the [Goode drive](https://drive.google.com/drive/folders/1ZOYpTUa82_jCcxIdTmyr0LXQfvaM9vIy?usp=sharing) and [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/d/e1ccfff39ad541908bae/). In both locations, the electricity dataset is from 7/1/2016 and 7/2/2019, which is clearly not the [UCI electricity dataset](https://archive.ics.uci.edu/dataset/321/electricityloaddiagrams20112014)  from 2011-2014. 

2. The [UCI electricity dataset](https://archive.ics.uci.edu/dataset/321/electricityloaddiagrams20112014) mentions 370 users, but the paper mentioned 321.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your question.
（1）The time stamps in electricity is added by us and not correctly matched to the real world. We add this just for temporal embedding. Thus, the relative interval is essential but the exact value will not affact the final performance.
（2）We obtain the data from this repo https://github.com/laiguokun/multivariate-time-series-data, which contains 321 variates.
