### ISSUE TITLE
exp_main:test/predict 中把label也作为decoder的输入了

### ISSUE THREAD

**Issue by deng113jie** [thuml/Autoformer#177]
https://github.com/thuml/Autoformer/blob/ab192380693bd04a1dc8aa6ff85addefcf0cf909/exp/exp_main.py#L206

是不是少了target mask？

**Comment by wuhaixu2016** [comment]
您好，请见：https://github.com/thuml/Autoformer/blob/ab192380693bd04a1dc8aa6ff85addefcf0cf909/exp/exp_main.py#L212C88-L212C88
会在后面步骤中将batch_y遮住，所以不会有未来泄漏的问题
