### ISSUE TITLE
如何用没有归一化的数据去做预测

### ISSUE THREAD

**Issue by manhaoran** [thuml/Autoformer#178]

**Comment by wuhaixu2016** [comment]
您好，如果没有归一化，可能会对预测结果造成较大影响，因为会损害深度模型的训练。
（1）我们在这篇文章中探索了新的归一化方式：https://openreview.net/forum?id=ucNDIDRNjjv
（2）如果您需要的是反归一化结果的话，可以使用inverse_transform函数

**Comment by rrrework** [comment]
您好，请问如何使用inverse_transform函数呀
