### ISSUE TITLE
Hi I have some questions about ./scripts

### ISSUE THREAD

**Issue by superblackwoo** [thuml/Autoformer#18]
你好！
我在Traffic数据集上进行Autoformer和Informer 的Multivariate预测的时候，运行 `./scripts/Traffic_script/Autoformer.sh` 得到的结果和论文中的结果接近，但是运行`./scripts/Traffic_script/Informer.sh`的时候有报错`RuntimeError: Given groups=1, weight of size [512, 1, 3], expected input[32, 862, 98] to have 1 channels, but got 862 channels instead`。个人认为是脚本中的参数：`--enc_in 1 --dec_in 1 --c_out 1` 有问题。对于Multivariate的预测，参数应该设置为`--enc_in 862 --dec_in 862 --c_out 862`

**Comment by superblackwoo** [comment]
当我把脚本./scripts/Traffic_script/Informer.sh 的参数改为-enc_in 862 --dec_in 862 --c_out 862之后，模型能进行训练，但是最终在Traffic数据集上的测试结果为：
96，mse:0.749122142791748, mae:0.4168018102645874
192，mse:0.7504376173019409, mae:0.4241149425506592 
336， mse:0.8584909439086914, mae:0.48440316319465637
720，mse:1.000118374824524, mae:0.5619020462036133

与Table 1：Multivariate results 中Informer的baseline相差比较大
96，mse:0.719, mae:0.391 
192，mse:0.696 , mae:0.379 
336， mse:0.777, mae:0.420
720，mse:0.864, mae:0.472

请问要如果想得到与paper中一样的结果，在训练Informer的时候的参数是怎么设置的呢？

**Comment by wuhaixu2016** [comment]
Hi, Thanks for your interest.

This repo mainly focuses on the comparison between attention modules. You can refer to the official public code of Informer for reproducing baselines.

**Comment by superblackwoo** [comment]
thanks！
