### ISSUE TITLE
关于autocorrelation的一些不解之处

### ISSUE THREAD

**Issue by qiyuxinlin** [thuml/Autoformer#181]
作者您好，我在阅读您的代码时，有些地方不是很理解，在对queries和keys求rfft之后，为什么求q_fft和k_fft的共轭的乘积？这里为什么不像self attention机制那样求q_fft和k_fft的矩阵乘？不好意思，我的数学基础比较薄弱，这个地方不是很理解，您论文中公式6的第一个式子中QK的autocorrelation应该就是求共轭吧？
![image](https://github.com/thuml/Autoformer/assets/44601537/41aae1eb-2f1d-4794-936a-e3b2709cd9ef)

**Comment by wuhaixu2016** [comment]
您好，请见：https://en.wikipedia.org/wiki/Autocorrelation#Wiener%E2%80%93Khinchin_theorem
