### ISSUE TITLE
--do_predict does not handle --features MS correctly

### ISSUE THREAD

**Issue by mw66** [thuml/Autoformer#182]
With  --features M, the test output pred.npy shape is (1422, 96, 8), and real_prediction.npy shape is (1, 96, 8)

With  --features MS, the test output pred.npy shape is (1422, 96, 1), and real_prediction.npy shape is *still* (1, 96, 8)

```
>>> import numpy as np
>>> p = np.load("./results/Exchange_96_96_Autoformer_custom_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/pred.npy")
>>> p.shape
(1422, 96, 1)
>>> p = np.load("./results/Exchange_96_96_Autoformer_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/pred.npy")
>>> p.shape
(1422, 96, 8)
>>> p = np.load("./results/Exchange_96_96_Autoformer_custom_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/real_prediction.npy")
>>> p.shape
(1, 96, 8)
>>> p = np.load("./results/Exchange_96_96_Autoformer_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/real_prediction.npy")
>>> p.shape
(1, 96, 8)
```

**Comment by mw66** [comment]
specfiically:

the following line are in vali(), train(), and test()
```
                f_dim = -1 if self.args.features == 'MS' else 0
```

https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L77
https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L138
https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L228

BUT is not in predict():
https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L305

You really should re-factor this into a separate function to avoid code duplication.

**Comment by mw66** [comment]
this file has too much code-duplcation:

https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L62-L79

**Comment by wuhaixu2016** [comment]
Hi, thanks for your commit. We have made the code cleaner.
