### ISSUE TITLE
ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by Dyw08** [thuml/Autoformer#184]
您好，打扰一下，请问运行时发生错误如下：  File "D:\anaconda\envs\tf2\lib\site-packages\torch\utils\data\sampler.py", line 114, in num_samples
    return len(self.data_source)
ValueError: __len__() should return >= 0

我把第一列的标签已经改成‘date’,但是还是发生以上错误，我应该怎么处理？谢谢，麻烦了！

**Comment by wuhaixu2016** [comment]
您好，看样子可能是数据没有加载成功，您可以看看data_source到底加载出来是什么样子

**Comment by LIXIANGPW** [comment]
> 您好，打扰一下，请问运行时发生错误如下： File "D:\anaconda\envs\tf2\lib\site-packages\torch\utils\data\sampler.py", line 114, in num_samples return len(self.data_source) ValueError: **len**() should return >= 0
> 
> 我把第一列的标签已经改成‘date’,但是还是发生以上错误，我应该怎么处理？谢谢，麻烦了！
您好，请问您解决了吗？
