### ISSUE TITLE
作者你好，请问序列分解中未来值填充零和填充平均值是有相关文献参考吗？

### ISSUE THREAD

**Issue by ZPFPHD** [thuml/Autoformer#186]
分解时无法分解未来值这是正确的，但填充零和填充平均值的合理性是有相关研究吗？

**Comment by wuhaixu2016** [comment]
您好，序列分解是我们自己新提出的解决方案，未来填充值是按照“预想”组分的均值进行的，比如未来的周期部分应该均值为0，未来的趋势部分应该和过去差不多，具体您也可以试试别的手段。
