### ISSUE TITLE
Informer和原作者的结果不一样

### ISSUE THREAD

**Issue by ANTAGNIST** [thuml/Autoformer#187]
您好，我用Informer作者提供的Informer-main-2020与您写的Autoformer中的Informer都用同样的数据集跑了一遍，发现Autoformer中Informer的结果比Informer-main-2020中Informer的结果要差，想问您一下是什么原因。
数据集在我的仓库里
```
# Informer-main-2020.main.py
import argparse
import os
import torch

from exp.exp_informer import Exp_Informer

parser = argparse.ArgumentParser(description='SURGE HEIGHT FORCASTING')
parser.add_argument('--data', type=str, default='custom', help='data')
parser.add_argument('--root_path', type=str, default='./data/zeiyuyong/', help='root path of the data file')
parser.add_argument('--data_path', type=str, default='zeiyuyong2016_8_1to2017_10_31.csv', help='data file')
parser.add_argument('--features', type=str, default='S', help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')
parser.add_argument('--enc_in', type=int, default=1, help='encoder input size')
parser.add_argument('--dec_in', type=int, default=1, help='decoder input size')
parser.add_argument('--c_out', type=int, default=1, help='output size')
parser.add_argument('--target', type=str, default='surge_height', help='target feature in S or MS task')
parser.add_argument('--seq_len', type=int, default=96, help='input sequence length of Informer encoder')
parser.add_argument('--label_len', type=int, default=48, help='start token length of Informer decoder')
parser.add_argument('--pred_len', type=int, default=24, help='prediction sequence length')

parser.add_argument('--model', type=str, default='informer',help='model of experiment, options: [informer, informerstack, informerlight(TBD)]')
parser.add_argument('--freq', type=str, default='t', help='freq for time features encoding, options:[s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly], you can also use more detailed freq like 15min or 3h')
parser.add_argument('--checkpoints', type=str, default='./checkpoints/', help='location of model checkpoints')

parser.add_argument('--d_model', type=int, default=512, help='dimension of model')
parser.add_argument('--n_heads', type=int, default=8, help='num of heads')
parser.add_argument('--e_layers', type=int, default=2, help='num of encoder layers')
parser.add_argument('--d_layers', type=int, default=1, help='num of decoder layers')
parser.add_argument('--s_layers', type=str, default='3,2,1', help='num of stack encoder layers')
parser.add_argument('--d_ff', type=int, default=2048, help='dimension of fcn')
parser.add_argument('--moving_avg', type=int, default=25, help='window size of moving average')
parser.add_argument('--factor', type=int, default=5, help='probsparse attn factor')
parser.add_argument('--padding', type=int, default=0, help='padding type')
parser.add_argument('--distil', action='store_false', help='whether to use distilling in encoder, using this argument means not using distilling', default=True)
parser.add_argument('--dropout', type=float, default=0.05, help='dropout')
parser.add_argument('--attn', type=str, default='prob', help='attention used in encoder, options:[prob, full]')
parser.add_argument('--embed', type=str, default='timeF', help='time features encoding, options:[timeF, fixed, learned]')
parser.add_argument('--activation', type=str, default='gelu',help='activation')
parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')
parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')
parser.add_argument('--mix', action='store_false', help='use mix attention in generative decoder', default=True)
parser.add_argument('--cols', type=str, nargs='+', help='certain cols from the data files as the input features')
parser.add_argument('--num_workers', type=int, default=0, help='data loader num workers')
parser.add_argument('--itr', type=int, default=1, help='experiments times')
parser.add_argument('--train_epochs', type=int, default=6, help='train epochs')
parser.add_argument('--batch_size', type=int, default=128, help='batch size of train input data')
parser.add_argument('--patience', type=int, default=3, help='early stopping patience')
parser.add_argument('--learning_rate', type=float, default=0.0001, help='optimizer learning rate')
parser.add_argument('--des', type=str, default='test',help='exp description')
parser.add_argument('--loss', type=str, default='mse',help='loss function')
parser.add_argument('--lradj', type=str, default='type1',help='adjust learning rate')
parser.add_argument('--use_amp', action='store_true', help='use automatic mixed precision training', default=False)
parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)
parser.add_argument('--use_gpu', type=bool, default=True, help='use gpu')
parser.add_argument('--gpu', type=int, default=0, help='gpu')
parser.add_argument('--use_multi_gpu', action='store_true', help='use multiple gpus', default=False)
parser.add_argument('--devices', type=str, default='0,1,2,3',help='device ids of multile gpus')

args = parser.parse_args()

args.use_gpu = True if torch.cuda.is_available() and args.use_gpu else False

if args.use_gpu and args.use_multi_gpu:
    args.devices = args.devices.replace(' ','')
    device_ids = args.devices.split(',')
    args.device_ids = [int(id_) for id_ in device_ids]
    args.gpu = args.device_ids[0]

args.s_layers = [int(s_l) for s_l in args.s_layers.replace(' ','').split(',')]
args.detail_freq = args.freq
args.freq = args.freq[-1:]

print('Args in experiment:')
print(args)

Exp = Exp_Informer

for ii in range(args.itr):
    setting = '{}_{}_{}_{}_{}'.format(args.model, args.data, args.data_path,
                args.des, ii)

  exp = Exp(args) # set experiments
  print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
  exp.train(setting)
  
  print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
  exp.test(setting)

  if args.do_predict:
      print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
      exp.predict(setting, True)

  torch.cuda.empty_cache()
```

```
Autoforer.main.py
import argparse
import os
import torch
from exp.exp_main import Exp_Main
import random
import numpy as np

data_name = "2016_8_1to2017_10_31"
name_type = ""
model_type_list = ['Autoformer', 'Reformer', 'Informer']
for model_type in model_type_list:
    parser = argparse.ArgumentParser(description='surgeHeight')
    parser.add_argument('--is_training', type=int, default=1, help='status')
    parser.add_argument('--model_id', type=str, default='test', help='model id')
    parser.add_argument('--model', type=str, default=f'{model_type}',
                        help='model name, options: [Autoformer, Informer, Transformer, Reformer]')
    parser.add_argument('--bucket_size', type=int, default=4, help='for Reformer')
    parser.add_argument('--n_hashes', type=int, default=4, help='for Reformer')
    parser.add_argument('--features', type=str, default='S', help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')
    parser.add_argument('--enc_in', type=int, default=1, help='encoder input size')
    parser.add_argument('--dec_in', type=int, default=1, help='decoder input size')
    parser.add_argument('--c_out', type=int, default=1, help='output size')
    parser.add_argument('--target', type=str, default='surge_height', help='target feature in S or MS task')
    parser.add_argument('--seq_len', type=int, default=96, help='input sequence length of Informer encoder')
    parser.add_argument('--label_len', type=int, default=48, help='start token length of Informer decoder')
    parser.add_argument('--pred_len', type=int, default=24, help='prediction sequence length')

    parser.add_argument('--freq', type=str, default='h', help='freq for time features encoding, options:[s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly], you can also use more detailed freq like 15min or 3h')
    parser.add_argument('--checkpoints', type=str, default='./checkpoints/', help='location of model checkpoints')

    parser.add_argument('--d_model', type=int, default=512, help='dimension of model')
    parser.add_argument('--n_heads', type=int, default=8, help='num of heads')
    parser.add_argument('--e_layers', type=int, default=2, help='num of encoder layers')
    parser.add_argument('--d_layers', type=int, default=1, help='num of decoder layers')
    parser.add_argument('--s_layers', type=str, default='3,2,1', help='num of stack encoder layers')
    parser.add_argument('--d_ff', type=int, default=2048, help='dimension of fcn')
    parser.add_argument('--moving_avg', type=int, default=25, help='window size of moving average')
    parser.add_argument('--factor', type=int, default=5, help='probsparse attn factor')
    parser.add_argument('--padding', type=int, default=0, help='padding type')
    parser.add_argument('--distil', action='store_false', help='whether to use distilling in encoder, using this argument means not using distilling', default=True)
    parser.add_argument('--dropout', type=float, default=0.05, help='dropout')
    parser.add_argument('--attn', type=str, default='prob', help='attention used in encoder, options:[prob, full]')
    parser.add_argument('--embed', type=str, default='timeF', help='time features encoding, options:[timeF, fixed, learned]')
    parser.add_argument('--activation', type=str, default='gelu',help='activation')
    parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')
    parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')
    parser.add_argument('--mix', action='store_false', help='use mix attention in generative decoder', default=True)
    parser.add_argument('--cols', type=str, nargs='+', help='certain cols from the data files as the input features')
    parser.add_argument('--num_workers', type=int, default=0, help='data loader num workers')
    parser.add_argument('--itr', type=int, default=1, help='experiments times')
    parser.add_argument('--train_epochs', type=int, default=10, help='train epochs')
    parser.add_argument('--batch_size', type=int, default=128, help='batch size of train input data')
    parser.add_argument('--patience', type=int, default=3, help='early stopping patience')
    parser.add_argument('--learning_rate', type=float, default=0.0001, help='optimizer learning rate')
    parser.add_argument('--des', type=str, default='test',help='exp description')
    parser.add_argument('--loss', type=str, default='mse',help='loss function')
    parser.add_argument('--lradj', type=str, default='type1',help='adjust learning rate')
    parser.add_argument('--use_amp', action='store_true', help='use automatic mixed precision training', default=False)
    parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)

    parser.add_argument('--use_gpu', type=bool, default=True, help='use gpu')
    parser.add_argument('--gpu', type=int, default=0, help='gpu')
    parser.add_argument('--use_multi_gpu', action='store_true', help='use multiple gpus', default=False)
    parser.add_argument('--devices', type=str, default='0,1,2,3',help='device ids of multile gpus')

    args = parser.parse_args()

    args.use_gpu = True if torch.cuda.is_available() and args.use_gpu else False

    if args.use_gpu and args.use_multi_gpu:
        args.devices = args.devices.replace(' ','')
        device_ids = args.devices.split(',')
        args.device_ids = [int(id_) for id_ in device_ids]
        args.gpu = args.device_ids[0]

    args.s_layers = [int(s_l) for s_l in args.s_layers.replace(' ','').split(',')]
    args.detail_freq = args.freq
    args.freq = args.freq[-1:]

    print('Args in experiment:')
    print(args)

    Exp = Exp_Main

    for ii in range(args.itr):
        setting = '{}_{}_{}'.format( args.model, args.data, args.data_path)

        exp = Exp(args) # set experiments
        print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
        exp.train(setting)

        print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
        exp.test(setting)

        if args.do_predict:
            print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
            exp.predict(setting, True)

        torch.cuda.empty_cache()
```

**Comment by ANTAGNIST** [comment]
> 您好，我用Informer作者提供的Informer-main-2020与您写的Autoformer中的Informer都用同样的数据集跑了一遍，发现Autoformer中Informer的结果比Informer-main-2020中Informer的结果要差，想问您一下是什么原因。 数据集在我的仓库里
> 
> ```
> # Informer-main-2020.main.py
> import argparse
> import os
> import torch
> 
> from exp.exp_informer import Exp_Informer
> 
> parser = argparse.ArgumentParser(description='SURGE HEIGHT FORCASTING')
> parser.add_argument('--data', type=str, default='custom', help='data')
> parser.add_argument('--root_path', type=str, default='./data/zeiyuyong/', help='root path of the data file')
> parser.add_argument('--data_path', type=str, default='zeiyuyong2016_8_1to2017_10_31.csv', help='data file')
> parser.add_argument('--features', type=str, default='S', help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')
> parser.add_argument('--enc_in', type=int, default=1, help='encoder input size')
> parser.add_argument('--dec_in', type=int, default=1, help='decoder input size')
> parser.add_argument('--c_out', type=int, default=1, help='output size')
> parser.add_argument('--target', type=str, default='surge_height', help='target feature in S or MS task')
> parser.add_argument('--seq_len', type=int, default=96, help='input sequence length of Informer encoder')
> parser.add_argument('--label_len', type=int, default=48, help='start token length of Informer decoder')
> parser.add_argument('--pred_len', type=int, default=24, help='prediction sequence length')
> 
> parser.add_argument('--model', type=str, default='informer',help='model of experiment, options: [informer, informerstack, informerlight(TBD)]')
> parser.add_argument('--freq', type=str, default='t', help='freq for time features encoding, options:[s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly], you can also use more detailed freq like 15min or 3h')
> parser.add_argument('--checkpoints', type=str, default='./checkpoints/', help='location of model checkpoints')
> 
> parser.add_argument('--d_model', type=int, default=512, help='dimension of model')
> parser.add_argument('--n_heads', type=int, default=8, help='num of heads')
> parser.add_argument('--e_layers', type=int, default=2, help='num of encoder layers')
> parser.add_argument('--d_layers', type=int, default=1, help='num of decoder layers')
> parser.add_argument('--s_layers', type=str, default='3,2,1', help='num of stack encoder layers')
> parser.add_argument('--d_ff', type=int, default=2048, help='dimension of fcn')
> parser.add_argument('--moving_avg', type=int, default=25, help='window size of moving average')
> parser.add_argument('--factor', type=int, default=5, help='probsparse attn factor')
> parser.add_argument('--padding', type=int, default=0, help='padding type')
> parser.add_argument('--distil', action='store_false', help='whether to use distilling in encoder, using this argument means not using distilling', default=True)
> parser.add_argument('--dropout', type=float, default=0.05, help='dropout')
> parser.add_argument('--attn', type=str, default='prob', help='attention used in encoder, options:[prob, full]')
> parser.add_argument('--embed', type=str, default='timeF', help='time features encoding, options:[timeF, fixed, learned]')
> parser.add_argument('--activation', type=str, default='gelu',help='activation')
> parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')
> parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')
> parser.add_argument('--mix', action='store_false', help='use mix attention in generative decoder', default=True)
> parser.add_argument('--cols', type=str, nargs='+', help='certain cols from the data files as the input features')
> parser.add_argument('--num_workers', type=int, default=0, help='data loader num workers')
> parser.add_argument('--itr', type=int, default=1, help='experiments times')
> parser.add_argument('--train_epochs', type=int, default=6, help='train epochs')
> parser.add_argument('--batch_size', type=int, default=128, help='batch size of train input data')
> parser.add_argument('--patience', type=int, default=3, help='early stopping patience')
> parser.add_argument('--learning_rate', type=float, default=0.0001, help='optimizer learning rate')
> parser.add_argument('--des', type=str, default='test',help='exp description')
> parser.add_argument('--loss', type=str, default='mse',help='loss function')
> parser.add_argument('--lradj', type=str, default='type1',help='adjust learning rate')
> parser.add_argument('--use_amp', action='store_true', help='use automatic mixed precision training', default=False)
> parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)
> parser.add_argument('--use_gpu', type=bool, default=True, help='use gpu')
> parser.add_argument('--gpu', type=int, default=0, help='gpu')
> parser.add_argument('--use_multi_gpu', action='store_true', help='use multiple gpus', default=False)
> parser.add_argument('--devices', type=str, default='0,1,2,3',help='device ids of multile gpus')
> 
> args = parser.parse_args()
> 
> args.use_gpu = True if torch.cuda.is_available() and args.use_gpu else False
> 
> if args.use_gpu and args.use_multi_gpu:
>     args.devices = args.devices.replace(' ','')
>     device_ids = args.devices.split(',')
>     args.device_ids = [int(id_) for id_ in device_ids]
>     args.gpu = args.device_ids[0]
> 
> args.s_layers = [int(s_l) for s_l in args.s_layers.replace(' ','').split(',')]
> args.detail_freq = args.freq
> args.freq = args.freq[-1:]
> 
> print('Args in experiment:')
> print(args)
> 
> Exp = Exp_Informer
> 
> for ii in range(args.itr):
>     setting = '{}_{}_{}_{}_{}'.format(args.model, args.data, args.data_path,
>                 args.des, ii)
> 
>   exp = Exp(args) # set experiments
>   print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
>   exp.train(setting)
>   
>   print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
>   exp.test(setting)
> 
>   if args.do_predict:
>       print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
>       exp.predict(setting, True)
> 
>   torch.cuda.empty_cache()
> ```
> 
> ```
> Autoforer.main.py
> import argparse
> import os
> import torch
> from exp.exp_main import Exp_Main
> import random
> import numpy as np
> 
> data_name = "2016_8_1to2017_10_31"
> name_type = ""
> model_type_list = ['Autoformer', 'Reformer', 'Informer']
> for model_type in model_type_list:
>     parser = argparse.ArgumentParser(description='surgeHeight')
>     parser.add_argument('--is_training', type=int, default=1, help='status')
>     parser.add_argument('--model_id', type=str, default='test', help='model id')
>     parser.add_argument('--model', type=str, default=f'{model_type}',
>                         help='model name, options: [Autoformer, Informer, Transformer, Reformer]')
>     parser.add_argument('--bucket_size', type=int, default=4, help='for Reformer')
>     parser.add_argument('--n_hashes', type=int, default=4, help='for Reformer')
>     parser.add_argument('--features', type=str, default='S', help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')
>     parser.add_argument('--enc_in', type=int, default=1, help='encoder input size')
>     parser.add_argument('--dec_in', type=int, default=1, help='decoder input size')
>     parser.add_argument('--c_out', type=int, default=1, help='output size')
>     parser.add_argument('--target', type=str, default='surge_height', help='target feature in S or MS task')
>     parser.add_argument('--seq_len', type=int, default=96, help='input sequence length of Informer encoder')
>     parser.add_argument('--label_len', type=int, default=48, help='start token length of Informer decoder')
>     parser.add_argument('--pred_len', type=int, default=24, help='prediction sequence length')
> 
>     parser.add_argument('--freq', type=str, default='h', help='freq for time features encoding, options:[s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly], you can also use more detailed freq like 15min or 3h')
>     parser.add_argument('--checkpoints', type=str, default='./checkpoints/', help='location of model checkpoints')
> 
>     parser.add_argument('--d_model', type=int, default=512, help='dimension of model')
>     parser.add_argument('--n_heads', type=int, default=8, help='num of heads')
>     parser.add_argument('--e_layers', type=int, default=2, help='num of encoder layers')
>     parser.add_argument('--d_layers', type=int, default=1, help='num of decoder layers')
>     parser.add_argument('--s_layers', type=str, default='3,2,1', help='num of stack encoder layers')
>     parser.add_argument('--d_ff', type=int, default=2048, help='dimension of fcn')
>     parser.add_argument('--moving_avg', type=int, default=25, help='window size of moving average')
>     parser.add_argument('--factor', type=int, default=5, help='probsparse attn factor')
>     parser.add_argument('--padding', type=int, default=0, help='padding type')
>     parser.add_argument('--distil', action='store_false', help='whether to use distilling in encoder, using this argument means not using distilling', default=True)
>     parser.add_argument('--dropout', type=float, default=0.05, help='dropout')
>     parser.add_argument('--attn', type=str, default='prob', help='attention used in encoder, options:[prob, full]')
>     parser.add_argument('--embed', type=str, default='timeF', help='time features encoding, options:[timeF, fixed, learned]')
>     parser.add_argument('--activation', type=str, default='gelu',help='activation')
>     parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')
>     parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')
>     parser.add_argument('--mix', action='store_false', help='use mix attention in generative decoder', default=True)
>     parser.add_argument('--cols', type=str, nargs='+', help='certain cols from the data files as the input features')
>     parser.add_argument('--num_workers', type=int, default=0, help='data loader num workers')
>     parser.add_argument('--itr', type=int, default=1, help='experiments times')
>     parser.add_argument('--train_epochs', type=int, default=10, help='train epochs')
>     parser.add_argument('--batch_size', type=int, default=128, help='batch size of train input data')
>     parser.add_argument('--patience', type=int, default=3, help='early stopping patience')
>     parser.add_argument('--learning_rate', type=float, default=0.0001, help='optimizer learning rate')
>     parser.add_argument('--des', type=str, default='test',help='exp description')
>     parser.add_argument('--loss', type=str, default='mse',help='loss function')
>     parser.add_argument('--lradj', type=str, default='type1',help='adjust learning rate')
>     parser.add_argument('--use_amp', action='store_true', help='use automatic mixed precision training', default=False)
>     parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)
> 
>     parser.add_argument('--use_gpu', type=bool, default=True, help='use gpu')
>     parser.add_argument('--gpu', type=int, default=0, help='gpu')
>     parser.add_argument('--use_multi_gpu', action='store_true', help='use multiple gpus', default=False)
>     parser.add_argument('--devices', type=str, default='0,1,2,3',help='device ids of multile gpus')
> 
>     args = parser.parse_args()
> 
>     args.use_gpu = True if torch.cuda.is_available() and args.use_gpu else False
> 
>     if args.use_gpu and args.use_multi_gpu:
>         args.devices = args.devices.replace(' ','')
>         device_ids = args.devices.split(',')
>         args.device_ids = [int(id_) for id_ in device_ids]
>         args.gpu = args.device_ids[0]
> 
>     args.s_layers = [int(s_l) for s_l in args.s_layers.replace(' ','').split(',')]
>     args.detail_freq = args.freq
>     args.freq = args.freq[-1:]
> 
>     print('Args in experiment:')
>     print(args)
> 
>     Exp = Exp_Main
> 
>     for ii in range(args.itr):
>         setting = '{}_{}_{}'.format( args.model, args.data, args.data_path)
> 
>         exp = Exp(args) # set experiments
>         print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
>         exp.train(setting)
> 
>         print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
>         exp.test(setting)
> 
>         if args.do_predict:
>             print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
>             exp.predict(setting, True)
> 
>         torch.cuda.empty_cache()
> ```

今晚又跑了一下，发现可能是我改动了源码中某些地方导致模型跑的有问题了。这个issue可以删除吗，我删不掉QAQ

**Comment by wuyulong666** [comment]
@ANTAGNIST 你好像把代码改过了对吧，我看了一下，Autoformer的作者，没有设置inverse，你是仿照Informer的方法加上了？右上角的issues似乎可以关闭自己创建的issue.

**Comment by wuhaixu2016** [comment]
感谢关注，感谢 @wuyulong666 解答，我关掉这个issue啦

**Comment by ANTAGNIST** [comment]
非常抱歉现在才看到消息，我确实仿照了Informer的作者将代码加上了inverse，但是这样反而弄巧成拙；之后我借鉴了CSDN（
https://blog.csdn.net/weixin_43149598/article/details/129109974
）这个作者的代码才得以反归一化成功。

wuyulong666 ***@***.***> 于2023年9月19日周二 16:34写道：

**Comment by ANTAGNIST** [comment]
谢谢你的帮助！

wuhaixu2016 ***@***.***> 于2023年9月20日周三 12:09写道：
