### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by aminshabani** [thuml/Autoformer#19]
Hi, Thank you so much for your code and I really like your interesting paper. 
I have a question on generating the results. When I use the docker and run the script I get:

```
ECL_96_96_Autoformer_custom_ftM_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0
mse:0.20583173632621765, mae:0.3203032612800598

ECL_96_192_Autoformer_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0
mse:0.24435684084892273, mae:0.34420478343963623

ECL_96_336_Autoformer_custom_ftM_sl96_ll48_pl336_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0
mse:0.23177462816238403, mae:0.3394138813018799

ECL_96_720_Autoformer_custom_ftM_sl96_ll48_pl720_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0
mse:0.2570257782936096, mae:0.35937315225601196
```

Although they are very close to the reported number, In the paper, it says each number is after 3 experiments, I was wondering should I change the iteration to 3 in the script to get the exact numbers? In another [recent paper](https://arxiv.org/pdf/2202.01381.pdf) I saw they got the same numbers using an average of 8 experiments.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.
(1) In this repo, we fix the seed as 2021. Thus, repeating will get the same results.
(2) You can delete the fixed seed and change the iteration to 3 to exactly reproduce the experiments.

**Comment by aminshabani** [comment]
Great! Thank you for your reply.
I thought the 3 experiments means having the same seed but changing the iter parameter to 3.

Thanks again.
