### ISSUE TITLE
Arima Baseline Model

### ISSUE THREAD

**Issue by pohlchri** [thuml/Autoformer#194]
Regarding the Arima Baseline Model I understand that you use pmdarima package and refit the model for every test batch e.g. every 48 values if this is the prediction length. However, can you give a bit more detail how you did the model training? Do you use some fixed input length for the Arima model to train on, if so which length? Otherwise in my experience this rolling window approach gets very time consuming. I would highly appreciate your help!

**Comment by wuhaixu2016** [comment]
Hi, we do adopt the rolling window approach to eval Arima baseline. It does take a lot of time.
