### ISSUE TITLE
每seq_len(N)预测下一步与每seq_len(N)预测下M步

### ISSUE THREAD

**Issue by gengi98** [thuml/Autoformer#198]
你好大佬，有几个问题请教
1.时序预测中关于每seq_len(N)预测下一步与每seq_len(N)预测下M步哪一个更符合预测这一主题
2.数据集较短（300）的数据预测是否适合Transformers族
3.2中提到的数据集因为data_loader好像受限较多，pred_len的空间较小，这种情况应该如何调整？(目前我的预测参数为pred_len:6 lable_len:3 pred_len:1)

**Comment by gengi98** [comment]
问题3中特指的每seq_len(N)预测下M步

**Comment by wuhaixu2016** [comment]
您好，我觉得预测下M步不错，另外因为你的数据集很小，其实建议先试试GDBT这些传统方法，也许有效果。
