### ISSUE TITLE
how to encode time

### ISSUE THREAD

**Issue by ShallowWill** [thuml/Autoformer#202]
你好，感谢提供代码。
我的数据是每隔5ms时间的数据，时间戳是这样的（单位为秒）：
`143.11139225, 143.11639562, 143.12139899, 143.12640236, 143.13140573, 143.1364091 , 143.14141247, 143.14641584, ... ...`
请问这样的时间我需要如何编码呢？代码中的time_features(）需要怎么改呢？

**Comment by wuhaixu2016** [comment]
您好，这种情况我建议使用类似pos embedding的方式，例如：https://github.com/thuml/Autoformer/blob/main/layers/Embed.py#L31
