### ISSUE TITLE
traffic数据集问题

### ISSUE THREAD

**Issue by Sunlandis** [thuml/Autoformer#203]
您好，我是做时序预测及现实意义解释性等研究，需要弄清数据集的具体参数意义。想问traffic数据集和paperswithcode中任何一个PeMS系列数据都对不上，能否给出预处理的过程呢？维度862，有一个是OT，我看了一下数值量级，最后一个OT应该也是某处传感器的数值吧？可以理解成用861处道路流量情况，和过去时间步的特征预测第862个道路情况吗？
另外想请问这个流量（0-1之间这个取值）的计算方式。我注意到PeMS08数据集的论文表现MAE都在14的量级，而traffic的表现都是在0.4的量级，显然这个数据单位是不同的，想请教数据与处理中的该862个道路占用率的计算方式，谢谢！

**Comment by wuhaixu2016** [comment]
您好，Traffic不是PEMS数据集。
Traffic数据集是：https://github.com/laiguokun/multivariate-time-series-data
如果您想跑PEMS可以看一下我们最新的论文：https://github.com/thuml/iTransformer
