### ISSUE TITLE
How to use your model with custom dataset

### ISSUE THREAD

**Issue by Maram-Helmy** [thuml/Autoformer#206]
Thanks for the great job!

Can you please guide me to how to use your model with my own dataset. I need to predict the charging time, where I take into account other factors such as weather data, days, Months which are categorical data. So how can I preprocess the dataset so it can be suitable an input for the model.

**Comment by shunsuke0-byte** [comment]
僕も同じ質問で、困っています

**Comment by wuhaixu2016** [comment]
Hi, you need to change you dataset as the same format as ETT datasets.
