### ISSUE TITLE
No postprocessing step

### ISSUE THREAD

**Issue by ItsJustIkenna** [thuml/Autoformer#207]
After the predictions are collected in the preds list, no postprocessing is done to transform the normalized predictions back to the original scale of the input data. The inverse_transform method in any of the dataset classes is never used. When I tried to implement it myself, the scale was incorrect. Can you update the code to correctly implement this?

**Comment by wuhaixu2016** [comment]
Hi, you may find this issue helpful: https://github.com/thuml/Autoformer/issues/6
