### ISSUE TITLE
关于moving_avg的问题

### ISSUE THREAD

**Issue by Et6an** [thuml/Autoformer#209]
十分感谢您的工作。遇到一个问题，我将moving_avg的res部分输出出来发现都是0，moving_mean部分输出的和原来的输入是一样的，并没有起到提取趋势的作用，请问为什么会出现这种情况？kernel_size=25，数据集是PJM2014负荷数据。
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.]]])

**Comment by wuhaixu2016** [comment]
您好，这个可能和你的数据本身有关（比如数据中大部分都是0，平滑之后就全都是0了），moving_avg是可以正常工作的。

**Comment by Et6an** [comment]
再次感谢
