### ISSUE TITLE
How to access preprocessing code for weather, illness, exchange..

### ISSUE THREAD

**Issue by junwoopark92** [thuml/Autoformer#21]
Thanks for the nice work.

I wonder how to get OT values in weather, illness, exchange datasets that this repository provides.

Can I access the preprocessing code?

Or, can I know how to get OT values in original data?

**Comment by junwoopark92** [comment]
yes I know I can download the preprocessed data from the cloud mentioned in Readme.

but, what I want to know is the preprocessing code to reproduce OT values, which not included in original data (weather, exchange, so on) 

The reason why I ask is that there are some outliers, which are -9999 in weather dataset.

I'm really sorry if I misunderstood.

**Comment by wuhaixu2016** [comment]
I see what you mean.

(1) OT is only for univariate time series forecasting. It is just a mark to point out the dimension of the univariate time series.
(2) Usually, we mark the last dimension as the OT. I think you can find the corresponding column in the original data easily.
(3) For the outlier, there are many mature tools to fix the time series, such as interpolation. You may find them useful.

**Comment by junwoopark92** [comment]
I understood! 
thanks a lot

**Comment by daihaozxn** [comment]
您好，如果我想在自己的数据集上进行单变量预测，我该如何处理原始数据得到这个OT列呢？
因为.csv文件中没有这个OT列，程序会报错。
