### ISSUE TITLE
illness数据集预处理代码

### ISSUE THREAD

**Issue by liuaohunter** [thuml/Autoformer#211]
你好，请问有没有illness数据集预处理的代码？
![9ZQBDB2@5CICW1E}NR@$)3Q](https://github.com/thuml/Autoformer/assets/121672391/9f947334-6a86-4501-b01a-7d8084705862)

**Comment by wuhaixu2016** [comment]
您好，如脚本中所写的，illness可以用Dataset_Custom处理
