### ISSUE TITLE
How to train the model with multiple CSVs files. 

### ISSUE THREAD

**Issue by Maram-Helmy** [thuml/Autoformer#217]
Hello Authors, 

Thank you for this great work.

I'm working with a dataset that consists of multiples CSVs files where each file represents certain activity, and it is sampled every 1 s, and the timestamps are non-overlapping. Therefore, each CSV file is independent from the others, but they are coming from the same process. is there a way to handle this? concatenating will not make sense.  

Your help is highly appreciated.

**Comment by wuhaixu2016** [comment]
Hi, I think this is pure engineering work. You can just modify the data loader code.

**Comment by 622Ruth** [comment]
> Hello Authors,
> 
> Thank you for this great work.
> 
> I'm working with a dataset that consists of multiples CSVs files where each file represents certain activity, and it is sampled every 1 s, and the timestamps are non-overlapping. Therefore, each CSV file is independent from the others, but they are coming from the same process. is there a way to handle this? concatenating will not make sense.
> 
> Your help is highly appreciated.

Hello, I'm encountering the same issue. May I ask if you have resolved it?
