### ISSUE TITLE
关于Auto-Correlation Mechanism的周期捕捉

### ISSUE THREAD

**Issue by xinyyhu** [thuml/Autoformer#219]
作者好！
想问一个小问题：
如果数据的周期较大（比如500个时间点是一个完整的周期），而input length小得多（如果按论文里的96的话），那么Auto-Correlation Mechanism是否还能有效捕捉数据周期信息。

**Comment by wuhaixu2016** [comment]
这个是不可以的。实际上，如果输入覆盖一个完整周期，那么其实模型都是在建模趋势信息。这种情况下可以增大输入长度，以让模型捕捉周期信息。
