### ISSUE TITLE
Using Custom Dataset with Different Input Lengths for Model

### ISSUE THREAD

**Issue by rozhix** [thuml/Autoformer#220]
My input dimensions are [1500, 50, 6] and my label dimensions are [1500, 1]. Can I use this model? If so, could you please explain how to configure it correctly?

**Comment by wuhaixu2016** [comment]
Sorry for the delayed response. I am not sure if I have correctly understood your question, I think it may be more like a classification task. You can see the dataloader of the classification task in TSlib (https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L616)
