### ISSUE TITLE
How is the ARIMA model Compared with Deep Models?

### ISSUE THREAD

**Issue by zhangzw16** [thuml/Autoformer#24]
Hello, I want to know how the baseline experiment of ARIMA is designed in the univariate experimental part? 

Especially in test evaluation, how do you use ARIMA to produce, say, L length output? Is it done in an autoregressive way, or use ARIMA to output L variables at one time? And do you re-fit the ARIMA model for every test batch (or step)?

**Comment by wuhaixu2016** [comment]
Hi, we adopt the pmdarima package, you can get more details here: https://pypi.org/project/pmdarima/
