### ISSUE TITLE
export CUDA_VISIBLE_DEVICES=1 disables CUDA

### ISSUE THREAD

**Issue by david-waterworth** [thuml/Autoformer#25]
Nice work!

I noticed though that on systems with 1 GPU, by default the scripts train on CPU. This is due to the bash files containing

`export CUDA_VISIBLE_DEVICES=1`

The issue is if you do this on a system with a single GPU the following returns false

`torch.cuda.is_available()`

Since the first GPU (normally) starts at 0

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

You can change the bash script to `export CUDA_VISIBLE_DEVICES=0` if the system only has 1 GPU.
