### ISSUE TITLE
User accessibility

### ISSUE THREAD

**Issue by strakehyr** [thuml/Autoformer#26]
Thank you for adding this amazing state-of-the-art model to python.

I wanted to ask if it could be possible to make the files easy to run directly from python, without requiring bash or Docker.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

Since the time series forecasting task has a lot of different settings, such as the model_name, input, prediction length, etc, I think the bash script version is simple and neat.

**Comment by strakehyr** [comment]
>  a lot of different settings, such as the model_name, input, prediction length, etc

Well a simple dictionary may suffice to store that data and have the run script run it with the respective dictionary to that dataset.

>  I think the bash script version is simple and neat.

As much as it might be neat, it can also be challenging for people trying to make this run on Windows. Specially for the majority of potential users of this script. Intorducing another language in the equation amplifies the potential troubleshooting you can run into. I am just saying, it would be a nice QoL addition and it should not cost a lot.
