### ISSUE TITLE
Baseline: Reformer

### ISSUE THREAD

**Issue by wcshin-git** [thuml/Autoformer#29]
Hi @wuhaixu2016, 
thanks for the great work!

Could I ask how you implemented Reformer in this time series forecasting problem?
In other words, I wonder whether you implemented Reformer in an autoregressive manner (i.e., predict one by one) or in your manner (i.e., predict multiple steps at once like Autoformer).

Lastly, I wonder if you have any plans to release the Reformer code soon.

Thank you!

**Comment by wuhaixu2016** [comment]
Hi, we use the reformer as "predict multiple steps at once like Autoformer". The one-step prediction is too slow and may have the accumulated error.

I will release the Reformer code this week.

**Comment by wuhaixu2016** [comment]
Hi, please see this commit: https://github.com/thuml/Autoformer/commit/0610c4fdc3d168fcf10cbc0c1cb223cd7d29b2c6
It is notable that Reformer is not proposed for time series forecasting, in that it cannot accomplish the cross attention.
Here is only one adaption in BERT-style (encoder-only), other possible implementations can also be acceptable.
