### ISSUE TITLE
Transformer.sh is reformer's experiments?

### ISSUE THREAD

**Issue by Masterleia** [thuml/Autoformer#30]
Hello, the Transformer.sh in the shell file is a comparative experiment of reformer? Is there a comparative experiment of reformer in the code？

**Comment by wuhaixu2016** [comment]
Hi, I have just uploaded the Reformer code.
But I have to remind that Reformer is not proposed for time series forecasting, in that it cannot accomplish the cross attention.
Here is only one adaption in BERT-style (encoder-only), other possible implementations can also be acceptable.

**Comment by Masterleia** [comment]
Thank you very much for your update


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Autoformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Autoformer] Transformer.sh is reformer's experiments? (Issue #30)





 
Hi, I have just uploaded the Reformer code.
 But I have to remind that Reformer is not proposed for time series forecasting, in that it cannot accomplish the cross attention.
 Here is only one adaption in BERT-style (encoder-only), other possible implementations can also be acceptable.
