### ISSUE TITLE
About the truncation of values and keys in AutoCorrelation

### ISSUE THREAD

**Issue by Yelrose** [thuml/Autoformer#34]
Hello, I am very curious about the truncation in AutoCorrelation for cross attention. Why the values are truncated by the first L elements but not the last L, which might be more correlated to the outputs.

https://github.com/thuml/Autoformer/blob/main/layers/AutoCorrelation.py#L111
```
 def forward(self, queries, keys, values, attn_mask):
        B, L, H, E = queries.shape
        _, S, _, D = values.shape
        if L > S:
            zeros = torch.zeros_like(queries[:, :(L - S), :]).float()
            values = torch.cat([values, zeros], dim=1)
            keys = torch.cat([keys, zeros], dim=1)
        else:
            values = values[:, :L, :, :]
            keys = keys[:, :L, :, :]
```

**Comment by wuhaixu2016** [comment]
Good point!

As your suggestion, the last L is more correlated. You can change this part to `keys[:, -L:, :, :]` and `values[:, -L:, :, :]`.

In our paper, most experiments are under the condition of `L>S`. You can try the above setting.
