### ISSUE TITLE
Questions about irregular time-series data

### ISSUE THREAD

**Issue by teemohold** [thuml/Autoformer#37]
Autoformer is an amazing work, and i studied much from your paper and your code. 
I have a dataset, irregular, the periodicity of my dataset is not obvious compared to datasets you choosen in your paper, such as ETT. 
I run Autoformer in my dataset, the qualitative results seem ok, but the qualitative (visualization) results are not good. Like the issue #35. 
Therefore, do you have any suggestions about the irregular time-series dataset without obvious periodicity ?

**Comment by wuhaixu2016** [comment]
(1) About irregular time series.
In my understanding, "irregular" means time series with different intervals between adjacent time points. In this context, I think Neural ODE or Decay RNN may be useful.

(2) About Time series without obvious periodicity.
We provide a case study in the Appendix for the Exchange dataset. The deep decomposition architecture is designed for this type of data. Maybe you can tune the hyper-parameter in moving average for better resutls.

**Comment by teemohold** [comment]
Thanks for your response. I think your response is very helpful.
