### ISSUE TITLE
关于预测的小疑问

### ISSUE THREAD

**Issue by chostorjax** [thuml/Autoformer#42]
给定一组数据，预测7天，Autoformer的输出是什么呢？（1）它是一次性把7天的数据都给预测出来呢？（2）还是类似于Lstm的单步预测一样，先预测第一天的值，紧接着再把第一天的值也归进数据里再进行预测第二天的值呢？

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

Please refer to the paper. It is clear that all transformer models are to predict the future at once.

**Comment by Zero-coder** [comment]
Different scenario have different demands, I guess`
