### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#44]
CPU: Intel i9-10900K (20) @ 5.300GHz 
  GPU: NVIDIA NVIDIA Corporation Devic 3090 24GB
Above is my device config.
The  training time is way too long,would you please tell me the concrete time you're using in training auto-former model.

**Comment by wuhaixu2016** [comment]
You can follow the instructions in Readme.txt. I think you can achieve a reasonable raining time easily.
