### ISSUE TITLE
little details debug

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#46]
`run.py` Line 57
`parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')`
Does the handsome Author want to say "whether to output attention in encoder,instead of 'ecoder'?"

**Comment by Zero-coder** [comment]
`parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')`
#是否预测未见的未来数据（不太理解this line）

**Comment by wuhaixu2016** [comment]
> `run.py` Line 57 `parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')` Does the handsome Author want to say "whether to output attention in encoder,instead of 'ecoder'?"

Thanks, we have fixed this.

**Comment by wuhaixu2016** [comment]
> `parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')` #是否预测未见的未来数据（不太理解this line）

This is for model serving. It will be helpful for the model development in real-world applications.

**Comment by Zero-coder** [comment]
thank you

> > `parser.add_argument('--do_predict', action='store_true', help='whether to predict unseen future data')` #是否预测未见的未来数据（不太理解this line）
> 
> This is for model serving. It will be helpful for the model development in real-world applications.

thanks for explaining
