### ISSUE TITLE
change d_layers and e_layers number

### ISSUE THREAD

**Issue by AliJavanJ1** [thuml/Autoformer#47]
I used Autoformer model in my project with double amount of e_layers and d_layers but model didn't work properly (returns nan output) specially on CPU
e_layers = 4
d_layers = 2
While debugging the  model, I understood that, nan outputs came from nn.LayerNorm in my_Layernorm class and also the second DecoderLayer in Decoder layers list

**Comment by Zero-coder** [comment]
Hello,I don't understand your point

**Comment by wuhaixu2016** [comment]
Hi, I think this problem is because of data.
(1) I have tested our model on all benchmarks in our paper with e_layers=4, d_layers=2. All the experiments are running successfully without nan.
(2) One possible way is to check if the data contains the nan values.
