### ISSUE TITLE
Why do we call torch.topk twice with the same input?

### ISSUE THREAD

**Issue by inspirit** [thuml/Autoformer#49]
Hello,
what is the reason for calling `torch.topk` with the same input but reading different outputs each time?
https://github.com/thuml/Autoformer/blob/6fd0883a9ebabec43c14fad95fcdd457c94d6e8c/layers/AutoCorrelation.py#L64-L65

**Comment by wuhaixu2016** [comment]
Hi, good point.
It will be faster if we combine these two operations.

**Comment by wuhaixu2016** [comment]
We have fixed this in https://github.com/thuml/Autoformer/commit/ff925fa7ed44e1c263d839be90e7bd7b86cd3c6c
