### ISSUE TITLE
Operation on Dataset

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#53]
`border1s = [0, 12 * 30 * 24 - self.seq_len, 12 * 30 * 24 + 4 * 30 * 24 - self.seq_len]
        border2s = [12 * 30 * 24, 12 * 30 * 24 + 4 * 30 * 24, 12 * 30 * 24 + 8 * 30 * 24]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]#没看懂

        if self.features == 'M' or self.features == 'MS':#输入
            cols_data = df_raw.columns[1:]#DataFrame.columns属性以返回给定 DataFrame 的列标签,这里不要date
            df_data = df_raw[cols_data]#再通过列名索引取出数据
        elif self.features == 'S':
            df_data = df_raw[[self.target]]#只取OT这一列作为输入

        if self.scale:#scale在_init_初始化True
            train_data = df_data[border1s[0]:border2s[0]]#不知道为什么可以问问author_wu
            self.scaler.fit(train_data.values)#简单来说，求得训练集的均值、方差、最大值、最小值等属性，对数据进行拟合
            data = self.scaler.transform(df_data.values)#在fit的基础上，进行归一化等
        else:
            data = df_data.values`  in data_provider  data_loader.py  Class Dataset_ETT_hour(Dataset)

Thanks for watching this,I wonder why and how you set the border and why  `train_data = df_data[border1s[0]:border2s[0]]`

**Comment by Zero-coder** [comment]
in data_provider  data_loader.py  Class Dataset_ETT_hour(Dataset)

**Comment by wuhaixu2016** [comment]
This is quite plain, you can print the intermediate results.
For more discussion, you can refer to https://github.com/thuml/Autoformer/issues/20

**Comment by Zero-coder** [comment]
Thank you very much for advice

**Comment by Zero-coder** [comment]
Simple explaination for train、val、test:[https://github.com/zhouhaoyi/Informer2020/issues/164](https://github.com/thuml/Autoformer/issues/url)

**Comment by Zero-coder** [comment]
border1s = [0, 12 * 30 * 24 - self.seq_len, 12 * 30 * 24 + 4 * 30 * 24 - self.seq_len]
        border2s = [12 * 30 * 24, 12 * 30 * 24 + 4 * 30 * 24, 12 * 30 * 24 + 8 * 30 * 24]
        border1 = border1s[self.set_type]#开始值，从数组border1s选一个值代表train、val、test
        border2 = border2s[self.set_type]#结束值，从数组border2s选一个值代表train、val、test
