### ISSUE TITLE
Baseline: TCN

### ISSUE THREAD

**Issue by Lip-Z** [thuml/Autoformer#54]
关于TCN baseline的问题: 看了并跑了一下关于TCN的代码, 好像都要求输出序列长度最多与输入序列长度相等, 大佬方便告知一下论文中TCN输入96预测192, 336,720是怎么实现的呢? 如何在train中进行loss的处理和回传?
感谢!

**Comment by wuhaixu2016** [comment]
Hi, you can use this in the autoregressive version just like rnns.

**Comment by vaeaea** [comment]
> 关于TCN baseline的问题: 看了并跑了一下关于TCN的代码, 好像都要求输出序列长度最多与输入序列长度相等, 大佬方便告知一下论文中TCN输入96预测192, 336,720是怎么实现的呢? 如何在train中进行loss的处理和回传? 感谢!

请问您弄清楚 预测长度大于输入长度时是怎么进行的了吗？ 我还是没看明白

**Comment by YangYu-NUAA** [comment]
You can use a MLP to fix its output length.
