### ISSUE TITLE
A colab.ipynb example for workflow

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#55]
[/home/fight/Desktop/Autoformer/Autoformer-main/predict.ipynb
](https://github.com/Zero-coder/Autoformer/blob/main/predict.ipynb)

**Comment by Zero-coder** [comment]
I create a colab example like informer does in his repository,hopeful this would help people by using amazing model autoformer

**Comment by wuhaixu2016** [comment]
Cool, thanks for your great work.

If you want, you can raise a pull request, then I can merge this into this repo (Just up to you)~

**Comment by Zero-coder** [comment]
sure,It's my pleasure
