### ISSUE TITLE
a little question about the top_k

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#58]
why k is defined as `where arg Topk(·) is to get the arguments of the Topk autocorrelations and let k = c × log Lc, c is a hyper-parameter.`,Does this follow the idea of Informer's "dominate-u query",because in Informer,it's dominate query u = c logL c as well.

**Comment by wuhaixu2016** [comment]
Yes, it is just like informer.
Actually,  if we set k as a constant, the complexity will be linear.

**Comment by Zero-coder** [comment]
get it,thanks
