### ISSUE TITLE
Seek for cooperation

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Autoformer#59]
Recently I'm working on my thesis,and I'm desperately for joining thuml,seek for cooperation in my thesis,if it's convenient for you(It's up to you~)

**Comment by Zero-coder** [comment]
If it's convenient for Mr.wu,I leave a message at you Zhihu,and hope for deeper communication.

**Comment by wuhaixu2016** [comment]
Hi, you can connect with my advisor Mingsheng Long (http://ise.thss.tsinghua.edu.cn/~mlong/) for details.

**Comment by Zero-coder** [comment]
appreciate for your response.
