### ISSUE TITLE
docker image doesn't build (windows)

### ISSUE THREAD

**Issue by onurbarut** [thuml/Autoformer#62]
Hi,

I wanted to build the docker image in my Win11 machine, but it failed while executing line 28 of Dockerfile:

> => ERROR [6/8] RUN conda install -n base -c conda-forge mamba 
> 
> ...
> #10 454.1 Found conflicts! Looking for incompatible packages.
> #10 454.1 This can take several minutes.  Press CTRL-C to abort.
> #10 454.1 failed
> #10 454.1
> #10 454.1 UnsatisfiableError: The following specifications were found
> #10 454.1 to be incompatible with the existing python installation in your environment:
> #10 454.1
> #10 454.1 Specifications:
> #10 454.1
> #10 454.1   - brotlipy -> python[version='3.10.*|3.4.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.9.10|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9|3.8.*|3.7.*|3.9.*',build='3_73_pypy|4_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|2_73_pypy|1_73_pypy|0_73_pypy']
> #10 454.1   - cffi -> python[version='2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.9.10|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|3.7.9|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|3.6.9|>=3.5,<3.6.0a0|3.4.*',build='3_73_pypy|4_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|2_73_pypy|1_73_pypy|0_73_pypy']
> #10 454.1   - cryptography -> python[version='3.10.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.9.10|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9|3.8.*|3.9.*|3.7.*|3.4.*|>=3.6|>=3.5|<=3.3',build='3_73_pypy|4_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|2_73_pypy|1_73_pypy|0_73_pypy']
> #10 454.1
> #10 454.1 Your python: python=3.9
> #10 454.1
> #10 454.1 If python is on the left-most side of the chain, that's the version you've asked for.
> #10 454.1 When python appears to the right, that indicates that the thing on the left is somehow
> #10 454.1 not available for the python version you are constrained to. Note that conda will not
> #10 454.1 change your python version to a different minor version unless you explicitly specify
> #10 454.1 that.
> #10 454.1
> #10 454.1 The following specifications were found to be incompatible with a past
> #10 454.1 explicit spec that is not an explicit spec in this operation (conda):
> #10 454.1
> #10 454.1   - mamba -> conda[version='4.6.*,<4.13.0|4.6.*|4.7.*,<4.13.0|>=4.7.12,<4.13.0|>=4.8,<4.13.0|>=4.7.12,<4.8']
> #10 454.1
> #10 454.1 The following specifications were found to be incompatible with each other:
> #10 454.1
> #10 454.1 Output in format: Requested package -> Available versions
> ....
> ....
> ....

It was a bit frustrating to get this error after waiting ~15 min. to build.

**Comment by wuhaixu2016** [comment]
Sorry, all the code of this repo is tested in Linux (I don't have a windows environment).
If you have a problem in the environment, I think do**not** use docker. Just follow the previous instruction and install the required package step by step.
