### ISSUE TITLE
A small question about finetuning

### ISSUE THREAD

**Issue by Daniel-Jiang358** [thuml/Autoformer#64]
Hello, I want to ask if I want to finetune, how to apply those already pretrained  .pth files? It seems that there isn't an interface to apply those   .pth files directly, so I have to train all the data by random initialization. Therefore, I want to know how to apply those pretrained parameters in the code. Thanks very much if you can give me an answer.

**Comment by Daniel-Jiang358** [comment]
Thank you

**Comment by wuhaixu2016** [comment]
Hi, 
(1) The pretrain problem in time series forecasting is still under exploration. From my experience, I think the pretrain model may be not helpful in this task.
(2) We do not focus on pretrain in the paper. If you want, you can add a `torch.load` before training, just like the test.
