### ISSUE TITLE
A small question about the cuda error 

### ISSUE THREAD

**Issue by Daniel-Jiang358** [thuml/Autoformer#67]
Hello, I'm a little bit confused about this situation, where the cuda is out of memory when I finished the inference. I tried debug, but I found it hard to understand that. 
Traceback (most recent call last):
  File "/data/jyq/Autoformer-main1/run.py", line 126, in <module>
    torch.cuda.empty_cache()
  File "/data/jyq/Anaconda3/envs/autoformer/lib/python3.6/site-packages/torch/cuda/memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by wuhaixu2016** [comment]
Can you provide more details about your experiment environment?
Like CUDA version or GPU device

**Comment by Daniel-Jiang358** [comment]
The cuda environment is 11.2, and I'm running on a severer with 4 2080ti gpus. Thank you.

**Comment by wuhaixu2016** [comment]
Yes, I think you can fix this on the single gpu.

**Comment by Daniel-Jiang358** [comment]
Yeah, but if I used one single cpu, even I set the batch size=4, the training still fails. 
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by shaido987** [comment]
It appears that using `torch.cuda.empty_cache()` will by default write data to gpu0 (~500MB). If there is data there already then this could give an out of memory error.

@Daniel-Jiang358: You could try adjusting the code to use something like

```python
with torch.cuda.device('cuda:1'):
    torch.cuda.empty_cache()
```
where `cuda:1` is whatever cuda you are running on.

References: https://discuss.pytorch.org/t/out-of-memory-when-i-use-torch-cuda-empty-cache/57898 and https://github.com/pytorch/pytorch/issues/25752

**Comment by Daniel-Jiang358** [comment]
It helps, you are right. Thank you very much.
