### ISSUE TITLE
关于 transformer 部分的疑问

### ISSUE THREAD

**Issue by h3z** [thuml/Autoformer#69]
你好大佬，我是 ai 新手，刚才在思考 n_head 的作用时候，发现在 `encoder` 中，`x` 分别经过全连接变为 `q, k, v`. 形状为 **(32, 8, 64, 96)** (输入时长是 96 )，感觉即使形状就保持 **(32, 512, 96)** 不必拆成 8*64 这样的 8 个头 似乎运算也是一样的？

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/28476985/177714234-e69e762a-ffbb-44b9-8de8-8817cd44d97c.png">

**Comment by h3z** [comment]
是不是 `time_delay_agg_training` 中为了性能，使得每个头使用了相同的 topk index，于是头和头间变得没区别了？
（如果哪里有常识性错误的话抱歉😂  摸索着自学的）

**Comment by wuhaixu2016** [comment]
是的不必拆开成8个头，如果想进一步提升效果的话，可以把8维度保留，对每个子空间求delay。

**Comment by h3z** [comment]
明白了，谢谢~

**Comment by Dojaron** [comment]
你好，请问一下这个图是怎么画出来的？很直观

**Comment by h3z** [comment]
> 你好，请问一下这个图是怎么画出来的？很直观

draw.io 画图工具，手画出来的😂
