### ISSUE TITLE
Informer实现中DecoderLayer部分与官方实现不一致

### ISSUE THREAD

**Issue by IncubatorShokuhou** [thuml/Autoformer#7]
https://github.com/thuml/Autoformer/blob/main/models/Informer.py#55
两层AttentionLayer中都是ProbAttention；

https://github.com/zhouhaoyi/Informer2020/blob/main/models/model.py#52
官方实现中第一层是ProbAttention，第二层是FullAttention

还有一些细节好像也不太一样，比如AttentionLayer中的mix参数。。。

**Comment by wuhaixu2016** [comment]
Hi, thanks for your suggestion.
(1) This repo mainly focuses on the self-attention mechanism comparison. For the Informer, the author has provided a great code: https://github.com/zhouhaoyi/Informer2020
(2) **if we use the full attention in Informer, the complexity will be O(L^2), which is different from the O(L log L) statement in their paper.**

**Comment by wuhaixu2016** [comment]
See nobody has questions on this issue. I would like to close this.
