### ISSUE TITLE
Could you share the intuition behind my_Layernorm?

### ISSUE THREAD

**Issue by maosi-chen** [thuml/Autoformer#70]
Wonderful work! 

Could your share your insight on the design and the usage of `my_Layernorm`?

1. After layer normalization on the feature/channel dimension, the bias (mean of sequence dimension for each batch and feature) was removed. Why is the removal of bias necessary (for the seasonal component)?

2. The original Transformer has layer normalization after every attention or feed forward operation, but Autoformer seems to only apply normalization after the last decoder. What is the intuition behind the choice?

Thanks!

**Comment by wuhaixu2016** [comment]
Hi, you can conduct ablation studies on these designs for more intuitive senses.
(1) Why is the removal of bias necessary?
This corresponds to the definition of autocorrelation, which is to remove the expectation for calculation
(2) Autoformer seems to only apply normalization after the last decoder.
I think you can still follow the vanilla transformer design, and the performance will be unchanged.
