### ISSUE TITLE
如何处理自己的数据集获得OT列

### ISSUE THREAD

**Issue by daihaozxn** [thuml/Autoformer#71]
您好，如果我想在自己的数据集上进行单变量预测，我该如何处理原始数据得到这个OT列呢？
因为.csv文件中没有这个OT列，程序会报错。

**Comment by wuhaixu2016** [comment]
可以读一下：https://github.com/thuml/Autoformer/blob/main/data_provider/data_loader.py
如果是多变量预测，那么将任意一个变量命名为OT即可。如果是单变量预测，则将带预测的变量命名为OT。

**Comment by daihaozxn** [comment]
明白了，谢谢
