### ISSUE TITLE
训练数据的长度要求

### ISSUE THREAD

**Issue by creamiracle** [thuml/Autoformer#73]
您好，感谢开源，在阅读了源码和相应数据后，想请教一下大概多长的数据可以应用呢？
例如两年天粒度的数据是否可以用来训练该网络？
谢谢

**Comment by wuhaixu2016** [comment]
您好，我们在论文附录中做了COVID-19的数据集，训练数据集也很少，效果也还可以。不过数据集肯定越大越好。
根据我的经验，训练数据集的timestamp的长度如果在5000以上，可以得到一个不错的预测效果。

**Comment by creamiracle** [comment]
> 您好，我们在论文附录中做了COVID-19的数据集，训练数据集也很少，效果也还可以。不过数据集肯定越大越好。 根据我的经验，训练数据集的timestamp的长度如果在5000以上，可以得到一个不错的预测效果。

您好，谢谢回复，我在一个测试数据上测试了一下，数据的形式是
| 时间 | 商品1 | 商品2 | 商品3 | ... | 商品18 |
时间长度全部截取了2年，不足的补0，测试效果并不是特别理想，可能是由于某些销量本身存在过多0的原因，这种有一定间歇性的数据的预测请问autoformer能有很好的应对么？
再次感谢。

**Comment by wuhaixu2016** [comment]
销售额如果不连续的是属于【事件数据】，这个问题本身比较困难，也许你需要先做一下数据的平滑，再进行预测

**Comment by creamiracle** [comment]
> 销售额如果不连续的是属于【事件数据】，这个问题本身比较困难，也许你需要先做一下数据的平滑，再进行预测

您这里的【事件数据】是指什么？

**Comment by wuhaixu2016** [comment]
https://arxiv.org/abs/2104.03528
您可以参考一下这篇综述文章⬆️

**Comment by creamiracle** [comment]
> 

如文章所述，那么您benchmark中的traffic或者covid数据集中出现了间断，是否也意味着不是【事件数据】？
