### ISSUE TITLE
Question regarding the multivariate setting

### ISSUE THREAD

**Issue by ChuckTG** [thuml/Autoformer#74]
Having set the features as multivariate, does it really matter which variable is the target? For example, if we had the dataset with variables a,b,c,d and we set d as the target variable, is d predicted better than a,b, or c? If I retrain the model with target value c, will then the d variable be forecasted less accurately or it will be the same as training with d as a target variable?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your questions.
We have three types of configurations for forecasting "MS", "M", and "S", corresponding to the argument `features`.
In the "M" configuration, there is no difference among different variables. However, for the "MS" setting, the loss function is only conducted on the target dimension. Note that the "MS" setting changes the multi-objection optimization problem to the single-objection optimization. Thus, in the "MS" setting, I think the target variable prediction will be better.

**Comment by ChuckTG** [comment]
Thanks for your reply!
