### ISSUE TITLE
关于使用自定义数据时遇到的问题

### ISSUE THREAD

**Issue by tc252617228** [thuml/Autoformer#75]
作者您好！我在使用模型的过程中发现，模型用在自己的风速数据集上的时候，mse最多到0.5的样子。
我查阅了之前其他人类似的问题。调整moving_avg, factor,d_model的参数，效果提升依旧有限。
这是我的数据集-某山地地形下的实测风速数据(通讯丢失后值不变)
[SPEED.csv](https://github.com/thuml/Autoformer/files/9159915/SPEED.csv)
希望作者能够提供一些建议。
非常感谢！

**Comment by wuhaixu2016** [comment]
感谢您的应用。
（1）您预期的MSE是多少呢？因为根据我的认知0.5已经是一个不错的结果了。
（2）我觉得您可以结合一下我们最新的Non-stationary Transformer的设计（https://arxiv.org/abs/2205.14415），因为风速的不平稳性会更加明显。
（3）如果是工程项目的话，我觉得可能是用模式数据或者其他气象要素会有很大帮助。

**Comment by tc252617228** [comment]
好的，感谢您的解答。

**Comment by BasinChen** [comment]
@tc252617228 您好，请问您在预测风速时是如何设置参数的呢，是用历史多少步预测未来的多少步？
