### ISSUE TITLE
--label len

### ISSUE THREAD

**Issue by H322** [thuml/Autoformer#77]
Hi 
what is the meaning of --label len?
In the code mentioned 'start token length', but does it mean that we have the labels until this timestep?
For example for using transformer with --seq_len 96, --label_len 48, and --pred_len 96, it means that we want to predict 96 step ahead using the previous 96 steps and we have the labels for the first 48 steps?
Thanks,

**Comment by wuhaixu2016** [comment]
Hi, 
"label" does not means the labeling for each time point. As stated in the paper, the label_len is just to provide the latest information for forecasting. 

This meaning is quite clear if you read the data_factory.py.
