### ISSUE TITLE
'NoneType' object is not subscriptable when running 'predict.ipynb'

### ISSUE THREAD

**Issue by erving666** [thuml/Autoformer#78]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/66522270/182762854-54542cba-22f8-49ab-8fa9-4948a4079f11.png">

---

TypeError                                 Traceback (most recent call last)
<ipython-input-14-9fc8431cad20> in <module>
      4 plt.figure()
      5 #预测OT
----> 6 plt.plot(prediction[-1,:,-1])#由于prediction.shape是[1,24,7]那么batch只有1 索引只能是0或-1 都是代表batch这一维本身
      7 print(prediction.shape)
      8 plt.show()

TypeError: 'NoneType' object is not subscriptable

**Comment by wuhaixu2016** [comment]
Hi, you can set the argument `do_predict` as True.
