### ISSUE TITLE
No such file or directory: './dataset/ETT-small/ETTh1.csv'

### ISSUE THREAD

**Issue by xuanhaodong** [thuml/Autoformer#80]
hi! I want to know that whether the data directory is not included in the project? 
I haven't found the directory in the project I downloaded !

**Comment by wuhaixu2016** [comment]
Hi, you can obtain the datasets from here: https://drive.google.com/drive/folders/1ZOYpTUa82_jCcxIdTmyr0LXQfvaM9vIy
