### ISSUE TITLE
The training process not even started

### ISSUE THREAD

**Issue by Daniel-Jiang358** [thuml/Autoformer#81]
Hello, I am running this code on my severer, however, the training process won't started while there are still normal gpu occupation.

**Comment by Daniel-Jiang358** [comment]
![3c96a7deaf7dd3f5d54833ba04c9676](https://user-images.githubusercontent.com/87486798/188528714-f8494ca9-5827-4d98-95e6-ab8e31d6ea3c.png)
![666adaf06d9fe326052eb55a9ba27f7](https://user-images.githubusercontent.com/87486798/188528853-31e9ff22-2a57-4dd8-a90c-f19087807518.png)
It has been stuck in this situation for very long time

**Comment by Daniel-Jiang358** [comment]
Some other codes can be run normally, and autoformer is not even started

**Comment by wuhaixu2016** [comment]
Are you using your own datasets? It will be very helpful if you provide a subset of your dataset.

**Comment by Daniel-Jiang358** [comment]
I have found the reasons. But would you please explain the reason that training on one A40-Link is much faster than multiple A40-Link? I tried other ones. Like A5000，3090，the same results. When I test on the ECL dataset on a5000，when using one card，each iter cost 0.04s，while on 8 cards，about 3s. I consider you abnormal.



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 6, 2022 16:43 PM
To: ***@***.***&gt;;
Cc: "Daniel ***@***.******@***.***&gt;;
Subject: Re: [thuml/Autoformer] The training process not even started (Issue#81)




 
Are you using your own datasets? It will be very helpful if you provide a subset of your dataset.

**Comment by wuhaixu2016** [comment]
I think time series forecasting is a light task. Maybe the multi-gpu training will cause extra communication costs.
