### ISSUE TITLE
Electricity dataset

### ISSUE THREAD

**Issue by mgreenbe** [thuml/Autoformer#88]
What is the precise relationship between the data in `electricity.csv` and the dataset from the [UCI Repository](https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014)? How, precisely is the latter preprocessed into the former?

In particular, the dates in the first column of `electricity.csv` are between 2016 and 2019, while the dates in the file from the UCI repository are between 2011 and 2014.

**Comment by wuhaixu2016** [comment]
Hi, the electricity dataset is from here.
https://github.com/laiguokun/multivariate-time-series-data
