### ISSUE TITLE
Results for univariate experiments

### ISSUE THREAD

**Issue by ddz16** [thuml/Autoformer#9]
Hello, could you provide the setting for univariate prediction? The results I run are a bit different from the results reported in the paper. I run the code according to the default setting.

python run.py --is_training 1 --root_path ./data/ --data_path ETTm2.csv --model_id ETTm2_96_96 --model Autoformer --data ETTm2 --features S --seq_len 96 --label_len 48 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des 'Exp' --itr 1
mse:0.1019936352968216, mae:0.2465277761220932
But the results in the paper are:       mse:0.065,    mae:0.189

python run.py --is_training 1 --root_path ./data/ --data_path ETTm2.csv --model_id ETTm2_96_336 --model Autoformer --data ETTm2 --features S --seq_len 96 --label_len 48 --pred_len 336 --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des 'Exp' --itr 1
mse:0.18364596366882324, mae:0.3304046392440796
But the results in the paper are:      mse:0.154,     mae:0.305

**Comment by gorold** [comment]
@wuhaixu2016 While the paper mentions that ETT refers to ETTm2 dataset for the multivariate experiments (Table 1), there is no mention of which variant ETT refers to in Table 2, could you please clarify if it is also ETTm2 for Table 2?

**Comment by wuhaixu2016** [comment]
> 

Sorry for the misleading. ETT means ETTm2 in Table 2.

**Comment by wuhaixu2016** [comment]
> @wuhaixu2016 While the paper mentions that ETT refers to ETTm2 dataset for the multivariate experiments (Table 1), there is no mention of which variant ETT refers to in Table 2, could you please clarify if it is also ETTm2 for Table 2?

Sorry for the misleading. Yes, in Table 2, ETT means ETTm2.

**Comment by wuhaixu2016** [comment]
Thanks for your interest! Sorry for the late reply (I am rushing on another work and close the git notification)

I have uploaded the univariate scripts. You can ref to https://github.com/thuml/Autoformer/commit/38a81558b53559f0653af7b36a58141e3bc7be7c
