### ISSUE TITLE
Handling of missing data and Temporal embedding

### ISSUE THREAD

**Issue by vaseline555** [thuml/Autoformer#90]
Hi, I enjoyed reading your work.

I am wondering about the handling of missing samples.
Usually, when we have missing points in temporal dataset, we have to interpolate them with a proper method.

Though in Autoformer, an explicit indicator of the temporal information (i.e., timestamp) is injected to the model in the form of temporal embedding.

In this case, even if we have missing time points, do we have to impute them?
I think the imputation for Autoformer is not mandatory as the model knows when each sample is collected.

Hope to get answers about this.
Thank you!

Best,
Adam

**Comment by wuhaixu2016** [comment]
I think you have two choices.
(1) Directly apply Autoformer without imputation. As you mentioned, the temporal embedding will promote the model to impute the missing data implicitly.
(2) Adopt Autoformer as an imputation model. You can firstly adopt the Autoformer to provide an initial value for the missing data. And then adopt Autoformer again to the imputed data for forecasting.

**Comment by vaseline555** [comment]
Thank you for your answer.
You mean, just adopting (1) without explicit imputation is a legit choice, right?
Thank you!
