### ISSUE TITLE
Different Inputs for use_amp flag, not sure if this is a bug.

### ISSUE THREAD

**Issue by yihaocs** [thuml/Autoformer#96]
Hello, 

I found that the inputs for the model is different when you use use_amp or not in your implementation: 
https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L132-L147 

In the code, if ``args.use_amp==True`` &  ``args.output_attention==False``, then we have

```Python

outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)  # L136

```

If if ``args.use_amp==False`` &  ``args.output_attention==False``, then we have 

```Python

outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark, batch_y) # L147

```

Is this specifically designed, or is this a bug? Because I find the implementation in the informer repo, they are consistent:

https://github.com/zhouhaoyi/Informer2020/blob/main/exp/exp_informer.py#L259-L283 : 

```Python

if self.args.use_amp:
    with torch.cuda.amp.autocast():
        if self.args.output_attention:
            outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
        else:
            outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
else:
    if self.args.output_attention:
        outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
    else:
        outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)

```

Thanks

**Comment by wuhaixu2016** [comment]
Sorry for this typo. We have fixed this in the latest commit.
