### ISSUE TITLE
数据集OT问题

### ISSUE THREAD

**Issue by TerrenceVarada** [thuml/Autoformer#97]
每个数据集都有一列OT，代码里定义OT是target。scripts里面的每个bash都定义--features M ，根据run的解释 M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate。既然只有一列OT，为什么feature不是MS?

**Comment by wuhaixu2016** [comment]
您好，具体任务和参数需要根据需求调整，如果想跑Multivariate forecasting，那就设置为M。如果想跑MS，那就设置为MS。具体请见数据加载代码：https://github.com/thuml/Autoformer/blob/main/data_provider/data_loader.py，相信读完这个代码，您会更清晰。
