### ISSUE TITLE
关于序列预测问题本身有些疑问

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Autoformer#98]
您好，首先非常感谢您的工作，很有启发！
关于时序回归我有一些问题想要问下您，代码中支持三种预测的模式，分别是'S', 'M', 'MS'，但是都属于自回归模式，如果我要预测的变量不属于输入中的变量，即我用A,B,C去预测D在未来时刻的信息，请问我应该如何构造我的encoder，decoder的输入呢？您有什么好的建议吗？

**Comment by wuhaixu2016** [comment]
您好，只需要将ABC作为输入，D作为监督信息即可，模型不用改动

**Comment by ownnaruto** [comment]
你好，我还是有个问题想问一下，就是如果我希望用t0 —— t1内的ABC去预测t0 —— t1内的D，并且每个时间步t只能使用t之前的相关信息，那么我直接 用autoformer是不是存在未来信息泄漏的问题？

**Comment by ownnaruto** [comment]
> 您好，只需要将ABC作为输入，D作为监督信息即可，模型不用改动

你好，我还是有个问题想问一下，就是如果我希望用t0 —— t1内的ABC去预测t0 —— t1内的D，并且每个时间步t只能使用t之前的相关信息，那么我直接 用autoformer是不是存在未来信息泄漏的问题？
