### ISSUE TITLE
No graph output when I run "predict.ipynb"

### ISSUE THREAD

**Issue by ziiayi** [thuml/Autoformer#99]
Hello, I am trying to run 'predict.ipynb' 

But it gives the following error: 
![image](https://user-images.githubusercontent.com/62853038/204113441-66f2f4df-29eb-4c11-96e7-c7aaf5a4a70e.png)

I have tried setting `args.do_predict = True`

But prediction is still returning 'NoneType':
![image](https://user-images.githubusercontent.com/62853038/204113480-515abbdb-509f-4042-8e02-b25d34caab6f.png)

How can I resolve this issue so that the prediction is done as intended.

**Comment by Zero-coder** [comment]
Hello,thanks for your feedback,I am gonna update this file immediately.

**Comment by Zero-coder** [comment]
I've updated this "predict.ipynb" file ,please pay attention for updating.

**Comment by ziiayi** [comment]
Thank you. It's working now.
